"""VibeSOP skill-craft command - Create skills from session history.

This command analyzes session history and creates reusable
skill definitions.

Usage:
    vibe skill-craft create
    vibe skill-craft from SESSION_FILE
    vibe skill-craft --help

Examples:
    # Create skill from current session
    vibe skill-craft create

    # Create skill from file
    vibe skill-craft from session.json

    # List skill templates
    vibe skill-craft templates
"""

from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel

console = Console()


def skill_craft(
    action: str = typer.Argument(..., help="Action: create, from, templates"),
    source: Optional[Path] = typer.Argument(
        None,
        help="Source session file",
        exists=True,
    ),
    name: Optional[str] = typer.Option(
        None,
        "--name",
        "-n",
        help="Skill name",
    ),
    description: Optional[str] = typer.Option(
        None,
        "--description",
        "-d",
        help="Skill description",
    ),
    output: Optional[Path] = typer.Option(
        None,
        "--output",
        "-o",
        help="Output directory",
    ),
) -> None:
    """Create skills from session history.

    This command analyzes conversation history and creates
    reusable skill definitions.

    \b
    Examples:
        # Create interactively from current session
        vibe skill-craft create

        # Create from session file
        vibe skill-craft from session.json

        # Create with custom name
        vibe skill-craft create --name "my-debug-skill"

        # List available templates
        vibe skill-craft templates
    """
    if action == "create":
        _do_create(source, name, description, output)
    elif action == "from":
        _do_from(source, name, description, output)
    elif action == "templates":
        _do_templates()
    else:
        console.print(
            f"[red]✗ Unknown action: {action}[/red]\n"
            f"[dim]Valid actions: create, from, templates[/dim]"
        )
        raise typer.Exit(1)


def _do_create(
    source: Path | None,
    name: str | None,
    description: str | None,
    output: Path | None,
) -> None:
    """Create skill interactively.

    Args:
        source: Optional source file
        name: Skill name
        description: Skill description
        output: Output directory
    """
    console.print(
        f"\n[bold cyan]🛠️  Skill Craft[/bold cyan]"
        f"\n{'=' * 40}\n"
    )

    console.print(
        Panel(
            "[bold]Skill Creation Wizard[/bold]\n\n"
            "This wizard will help you create a new skill.\n"
            "Skills are reusable workflows that can be triggered\n"
            "by specific situations or user requests.\n\n"
            "[dim]Press Ctrl+C to cancel[/dim]",
            border_style="cyan",
        )
    )

    # Collect skill information
    if not name:
        console.print("\n[bold]Step 1: Skill Name[/bold]")
        console.print("[dim]Enter a short, memorable name (e.g., 'debug-error')[/dim]")
        console.print("\n[dim]Skipping interactive mode - provide --name[/dim]")
        console.print("\n[dim]Example:[/dim]")
        console.print("  [cyan]vibe skill-craft create --name 'my-skill' --description 'My custom skill'[/dim]")
        raise typer.Exit(0)

    # Generate skill template
    skill_content = f"""# {name}

{description or 'A custom skill for VibeSOP.'}

## Trigger When

{f"User asks for help with: {name}" if not description else f"{description}"}

## Steps

1. Understand the user's request
2. Analyze the context
3. Provide appropriate assistance

## Examples

### Example 1

**User**: {name}

**Action**: Help the user with their request

---

*Generated by VibeSOP skill-craft*
"""

    # Write skill file
    output_dir = Path(output or ".vibe/skills")
    output_dir.mkdir(parents=True, exist_ok=True)

    skill_file = output_dir / f"{name.lower().replace(' ', '-')}.md"
    skill_file.write_text(skill_content)

    console.print(
        f"\n[green]✓ Skill created[/green]\n"
        f"  [dim]File:[/dim] {skill_file}\n"
    )
    console.print(
        f"\n[dim]Edit the skill file to customize behavior.[/dim]\n"
        f"[dim]After editing, run [cyan]vibe build[/cyan] to include it.[/dim]"
    )


def _do_from(
    source: Path | None,
    name: str | None,
    description: str | None,
    output: Path | None,
) -> None:
    """Create skill from source file.

    Args:
        source: Source session file
        name: Skill name
        description: Skill description
        output: Output directory
    """
    if not source:
        console.print("[red]✗ Source file required[/red]")
        console.print("[dim]Usage: vibe skill-craft from SESSION_FILE[/dim]")
        raise typer.Exit(1)

    console.print(
        f"\n[bold cyan]📄 Analyzing Session[/bold cyan]"
        f"\n{'=' * 40}\n"
    )

    console.print(f"[dim]Source: {source}[/dim]\n")

    # Read session file
    try:
        import json
        content = source.read_text()
        session = json.loads(content)

        console.print(f"[green]✓ Loaded session[/green]")
        console.print(f"  Messages: {len(session.get('messages', []))}")

        # Extract patterns
        console.print(f"\n[dim]Analyzing patterns...[/dim]")

        # TODO: Implement pattern extraction
        console.print(f"\n[dim]Pattern extraction not yet implemented[/dim]")
        console.print(f"\n[dim]Use --name and --description to create manually:[/dim]")
        console.print(f"  [cyan]vibe skill-craft from {source} --name 'my-skill'[/cyan]")

    except json.JSONDecodeError:
        console.print(f"[red]✗ Invalid JSON file[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")
        raise typer.Exit(1)


def _do_templates() -> None:
    """List available skill templates."""
    console.print(
        f"\n[bold cyan]📋 Skill Templates[/bold cyan]"
        f"\n{'=' * 40}\n"
    )

    templates = [
        ("debug", "Debugging and troubleshooting", "For systematic debugging workflows"),
        ("review", "Code review", "For reviewing code changes"),
        ("test", "Test generation", "For generating test cases"),
        ("document", "Documentation", "For writing documentation"),
        ("refactor", "Code refactoring", "For improving code structure"),
    ]

    for template_id, name, description in templates:
        console.print(f"  [cyan]{template_id}[/cyan] - {name}")
        console.print(f"    [dim]{description}[/dim]\n")

    console.print(
        f"\n[dim]Use: [cyan]vibe skill-craft create --name <name> --template <template>[/cyan][/dim]"
    )
