"""Tests for orchestration summary generation."""

import pytest

from vibesop.core.models import ExecutionMode, ExecutionPlan, ExecutionStep
from vibesop.core.orchestration.summary import _format_step, generate_execution_summary


class TestGenerateExecutionSummary:
    """Test generate_execution_summary function."""

    def _make_step(
        self,
        step_id: str = "s1",
        step_number: int = 1,
        skill_id: str = "test/skill",
        intent: str = "test intent",
        input_query: str = "do something",
        dependencies: list[str] | None = None,
        can_parallel: bool = True,
    ) -> ExecutionStep:
        return ExecutionStep(
            step_id=step_id,
            step_number=step_number,
            skill_id=skill_id,
            intent=intent,
            input_query=input_query,
            dependencies=dependencies or [],
            can_parallel=can_parallel,
        )

    def test_sequential_plan(self):
        """Summary for sequential plan should show ordered steps."""
        plan = ExecutionPlan(
            plan_id="p1",
            original_query="分析并修复bug",
            execution_mode=ExecutionMode.SEQUENTIAL,
            reasoning="需要先分析，再修复",
            steps=[
                self._make_step("s1", 1, "analyze", "分析代码", "分析这个bug"),
                self._make_step("s2", 2, "debug", "修复bug", "修复这个bug", dependencies=["s1"]),
            ],
        )
        summary = generate_execution_summary(plan)

        assert "# Execution Plan: 分析并修复bug" in summary
        assert "SEQUENTIAL" in summary
        assert "**Steps:** 2" in summary
        assert "> 需要先分析，再修复" in summary
        assert "## Sequential Execution" in summary
        assert "Step 1: 分析代码" in summary
        assert "Step 2: 修复bug" in summary
        assert "**Depends on:** s1" in summary
        assert "*Generated by VibeSOP*" in summary

    def test_parallel_plan(self):
        """Summary for parallel plan should show parallel execution section."""
        plan = ExecutionPlan(
            plan_id="p2",
            original_query="分析架构和文档",
            execution_mode=ExecutionMode.PARALLEL,
            steps=[
                self._make_step("s1", 1, "analyze", "分析架构", "分析系统架构"),
                self._make_step("s2", 2, "document", "更新文档", "更新API文档"),
            ],
        )
        summary = generate_execution_summary(plan)

        assert "## Parallel Execution" in summary
        assert "simultaneously" in summary
        assert "Step 1: 分析架构" in summary
        assert "Step 2: 更新文档" in summary

    def test_mixed_plan(self):
        """Summary for mixed plan should group steps into batches."""
        plan = ExecutionPlan(
            plan_id="p3",
            original_query="分析、修复并部署",
            execution_mode=ExecutionMode.MIXED,
            steps=[
                self._make_step("s1", 1, "analyze", "分析", "分析代码", dependencies=[]),
                self._make_step("s2", 2, "debug", "修复", "修复bug", dependencies=["s1"]),
                self._make_step("s3", 3, "deploy", "部署", "部署应用", dependencies=["s2"]),
            ],
        )
        summary = generate_execution_summary(plan)

        assert "## Mixed Execution" in summary
        assert "Batch" in summary

    def test_empty_plan(self):
        """Summary for empty plan should still render."""
        plan = ExecutionPlan(
            plan_id="p4",
            original_query="empty",
            execution_mode=ExecutionMode.SEQUENTIAL,
            steps=[],
        )
        summary = generate_execution_summary(plan)

        assert "**Steps:** 0" in summary
        assert "*Generated by VibeSOP*" in summary

    def test_no_reasoning(self):
        """Plan without reasoning should not include reasoning block."""
        plan = ExecutionPlan(
            plan_id="p5",
            original_query="test",
            execution_mode=ExecutionMode.SEQUENTIAL,
            reasoning="",
            steps=[self._make_step("s1", 1, "test", "测试", "运行测试")],
        )
        summary = generate_execution_summary(plan)

        assert "> " not in summary  # No reasoning block


class TestFormatStep:
    """Test _format_step helper."""

    def test_basic_formatting(self):
        """Step should be formatted with markdown."""
        step = ExecutionStep(
            step_id="s1",
            step_number=1,
            skill_id="test/skill",
            intent="测试",
            input_query="运行单元测试",
        )
        lines = _format_step(step)

        assert any("### Step 1: 测试" in line for line in lines)
        assert any("`test/skill`" in line for line in lines)
        assert any("运行单元测试" in line for line in lines)

    def test_with_dependencies(self):
        """Step with dependencies should show them."""
        step = ExecutionStep(
            step_id="s2",
            step_number=2,
            skill_id="fix",
            intent="修复",
            input_query="修复bug",
            dependencies=["s1"],
        )
        lines = _format_step(step, show_dependencies=True)

        assert any("**Depends on:** s1" in line for line in lines)

    def test_can_parallel(self):
        """Step that can run in parallel should indicate it."""
        step = ExecutionStep(
            step_id="s1",
            step_number=1,
            skill_id="test",
            intent="测试",
            input_query="test",
            can_parallel=True,
        )
        lines = _format_step(step)

        assert any("**Can run in parallel:** Yes" in line for line in lines)

    def test_indentation(self):
        """Indent should add leading spaces."""
        step = ExecutionStep(
            step_id="s1",
            step_number=1,
            skill_id="test",
            intent="测试",
            input_query="test",
        )
        lines = _format_step(step, indent=2)

        assert lines[0].startswith("    ### Step")
