# pyright: ignore[reportArgumentType]
"""技能自动理解和配置模块.

该模块提供了在非 Agent 环境(bash)中自动理解技能并生成配置的能力.

核心功能:
    1. 读取 SKILL.md
    2. 使用规则引擎分析技能
    3. 使用关键词分析理解技能用途
    4. 自动生成优先级、路由规则、LLM 配置
    5. 保存配置到 .vibe/skills/auto-config.yaml

使用方式:
    configurator = SkillAutoConfigurator()
    config = configurator.understand_and_configure(metadata, skill_content)
"""

import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, ClassVar

from vibesop.core.skills.base import SkillMetadata, SkillType

logger = logging.getLogger(__name__)


class ComplexityLevel(Enum):
    """技能复杂度"""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class UrgencyLevel(Enum):
    """紧急程度"""

    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class SkillAnalysis:
    """技能分析结果"""

    # 基本信息
    skill_type: SkillType = SkillType.PROMPT
    tags: list[str] = field(default_factory=list)

    # 分析结果
    categories: list[str] = field(default_factory=list)
    primary_category: str = "development"

    # 特征
    requires_llm: bool = False
    complexity: ComplexityLevel = ComplexityLevel.MEDIUM
    urgency: UrgencyLevel = UrgencyLevel.NORMAL

    # 关键词
    keywords: list[str] = field(default_factory=list)

    # 置信度
    confidence: float = 0.5


@dataclass
class AutoGeneratedConfig:
    """自动生成的配置"""

    skill_id: str
    category: str = "development"
    priority: int = 50
    enabled: bool = True
    scope: str = "project"

    # 路由配置
    routing_patterns: list[str] = field(default_factory=list)
    routing_priority: int = 0

    # LLM 配置
    requires_llm: bool = False
    llm_config: dict[str, Any] = field(default_factory=dict)

    # 元数据
    config_source: str = "auto_generated"
    confidence: float = 0.5
    analysis: SkillAnalysis | None = None


class SkillTypeRules:
    """基于技能类型的配置规则"""

    RULES: ClassVar[dict[SkillType, dict[str, Any]]] = {
        SkillType.PROMPT: {
            "default_priority": 60,
            "requires_llm": True,
            "llm_preference": "anthropic",
            "default_temperature": 0.7,
        },
        SkillType.WORKFLOW: {
            "default_priority": 50,
            "requires_llm": False,
            "multi_step": True,
        },
        SkillType.COMMAND: {
            "default_priority": 40,
            "requires_llm": False,
            "execution_type": "shell",
        },
        SkillType.HYBRID: {
            "default_priority": 70,
            "requires_llm": True,
            "complex": True,
        },
    }

    @classmethod
    def get_config(cls, skill_type: SkillType) -> dict[str, Any]:
        """获取技能类型的默认配置"""
        return cls.RULES.get(skill_type, {})


class CategoryRules:
    """基于类别的配置规则"""

    RULES: ClassVar[dict[str, dict[str, Any]]] = {
        "debugging": {
            "priority_range": (75, 95),
            "urgency": "high",
            "llm": {
                "provider": "anthropic",
                "models": ["claude-sonnet-4-6-20250514"],
                "temperature": 0.3,
            },
        },
        "testing": {
            "priority_range": (55, 75),
            "llm": {
                "provider": "anthropic",
                "models": ["claude-sonnet-4-6"],
                "temperature": 0.4,
            },
        },
        "review": {
            "priority_range": (50, 70),
            "llm": {
                "provider": "anthropic",
                "models": ["claude-3-5-sonnet-20241022"],
                "temperature": 0.2,
            },
        },
        "documentation": {
            "priority_range": (30, 50),
            "llm": {
                "provider": "anthropic",
                "models": ["claude-3-haiku-20240307"],
                "temperature": 0.5,
            },
        },
        "deployment": {
            "priority_range": (70, 90),
            "urgency": "high",
            "llm": None,
        },
        "security": {
            "priority_range": (80, 100),
            "urgency": "critical",
            "llm": {
                "provider": "anthropic",
                "models": ["claude-3-opus-20240229"],
                "temperature": 0.1,
            },
        },
        "brainstorming": {
            "priority_range": (40, 60),
            "llm": {
                "provider": "openai",
                "models": ["gpt-4"],
                "temperature": 0.9,
            },
        },
        "development": {
            "priority_range": (60, 80),
            "llm": {
                "provider": "anthropic",
                "models": ["claude-sonnet-4-6"],
                "temperature": 0.5,
            },
        },
        "optimization": {
            "priority_range": (50, 70),
            "llm": {
                "provider": "anthropic",
                "models": ["claude-sonnet-4-6"],
                "temperature": 0.3,
            },
        },
    }

    # 类别关键词映射
    CATEGORY_KEYWORDS: ClassVar[dict[str, list[str]]] = {
        "debugging": [
            "debug",
            "error",
            "bug",
            "fix",
            "troubleshoot",
            "diagnose",
            "调试",
            "错误",
            "故障",
            "修复",
            "诊断",
            "breakpoint",
            "stacktrace",
        ],
        "testing": [
            "test",
            "spec",
            "tdd",
            "verify",
            "check",
            "coverage",
            "测试",
            "验证",
            "检查",
            "用例",
            "单元测试",
            "回归",
        ],
        "review": [
            "review",
            "audit",
            "quality",
            "inspect",
            "analyze",
            "assess",
            "审查",
            "审计",
            "质量",
            "分析",
            "评估",
            "code review",
        ],
        "documentation": [
            "document",
            "doc",
            "readme",
            "guide",
            "tutorial",
            "handbook",
            "文档",
            "指南",
            "教程",
            "说明书",
            "手册",
        ],
        "deployment": [
            "deploy",
            "release",
            "publish",
            "ship",
            "cd",
            "ci/cd",
            "部署",
            "发布",
            "上线",
            "交付",
            "流水线",
        ],
        "security": [
            "security",
            "vulnerability",
            "scan",
            "audit",
            "exploit",
            "安全",
            "漏洞",
            "扫描",
            "渗透",
            "加固",
        ],
        "brainstorming": [
            "brainstorm",
            "idea",
            "creative",
            "innovate",
            "ideate",
            "头脑风暴",
            "创意",
            "创新",
            "发散",
            "构思",
        ],
        "optimization": [
            "optimize",
            "performance",
            "improve",
            "speed",
            "efficient",
            "优化",
            "性能",
            "改进",
            "提速",
            "效率",
        ],
        "planning": [
            "plan",
            "roadmap",
            "strategy",
            "estimate",
            "schedule",
            "规划",
            "计划",
            "路线",
            "策略",
            "排期",
        ],
    }

    # 基于技能 ID 前缀的类别映射(强信号)
    ID_CATEGORY_PREFIXES: ClassVar[dict[str, str]] = {
        "debug": "debugging",
        "error": "debugging",
        "bug": "debugging",
        "test": "testing",
        "spec": "testing",
        "tdd": "testing",
        "qa": "testing",
        "review": "review",
        "audit": "review",
        "inspect": "review",
        "doc": "documentation",
        "readme": "documentation",
        "guide": "documentation",
        "deploy": "deployment",
        "release": "deployment",
        "ship": "deployment",
        "publish": "deployment",
        "security": "security",
        "vuln": "security",
        "brainstorm": "brainstorming",
        "idea": "brainstorming",
        "optimize": "optimization",
        "perf": "optimization",
        "plan": "planning",
        "roadmap": "planning",
        "research": "development",
        "refactor": "development",
        "architect": "development",
        "design": "development",
        "investigate": "debugging",
    }

    @classmethod
    def infer_category(cls, metadata: SkillMetadata, content: str = "") -> str:
        """从元数据推断类别

        优先级: skill_id > tags > description/content > default
        """
        skill_id = metadata.id.lower()

        # 0. 从 skill ID 推断(最强信号)
        for prefix, category in cls.ID_CATEGORY_PREFIXES.items():
            if prefix in skill_id:
                return category

        # 1. 从 tags 推断
        if metadata.tags:
            tag_category_map = {
                "debug": "debugging",
                "test": "testing",
                "review": "review",
                "deploy": "deployment",
                "security": "security",
                "doc": "documentation",
                "brainstorm": "brainstorming",
                "optimize": "optimization",
                "plan": "planning",
            }

            for tag in metadata.tags:
                tag_lower = tag.lower()
                if tag_lower in tag_category_map:
                    return tag_category_map[tag_lower]

        # 2. 从 description 和 content 推断
        text = f"{metadata.description} {content}".lower()

        for category, keywords in cls.CATEGORY_KEYWORDS.items():
            if any(kw in text for kw in keywords):
                return category

        # 默认
        return "development"

    @classmethod
    def get_config(cls, category: str) -> dict[str, Any]:
        """获取类别的配置"""
        return cls.RULES.get(category, {})


class KeywordAnalyzer:
    """关键词分析器"""

    # 扩展的停用词列表
    STOP_WORDS: ClassVar[set[str]] = {
        # 英文
        "the",
        "a",
        "an",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "must",
        "shall",
        "can",
        "need",
        "for",
        "with",
        "from",
        "this",
        "that",
        "these",
        "those",
        "use",
        "using",
        "get",
        "got",
        "make",
        "made",
        "take",
        "took",
        "help",
        "user",
        "ask",
        "want",
        "like",
        "and",
        "or",
        "but",
        "not",
        "nor",
        "so",
        "yet",
        "after",
        "once",
        # 中文
        "用户",
        "帮助",
        "使用",
        "需要",
        "想要",
        "可以",
        "和",
        "或",
        "但是",
        "不",
    }

    # LLM 相关关键词
    LLM_KEYWORDS: ClassVar[list[str]] = [
        "ai",
        "llm",
        "gpt",
        "claude",
        "anthropic",
        "openai",
        "分析",
        "生成",
        "理解",
        "总结",
        "解释",
        "analyze",
        "generate",
        "understand",
        "summarize",
        "explain",
    ]

    # 复杂度关键词
    COMPLEXITY_KEYWORDS: ClassVar[dict[ComplexityLevel, list[str]]] = {
        ComplexityLevel.HIGH: [
            "complex",
            "architecture",
            "system",
            "multi",
            "framework",
            "复杂",
            "架构",
            "系统",
            "框架",
        ],
        ComplexityLevel.MEDIUM: [
            "module",
            "component",
            "feature",
            "function",
            "模块",
            "组件",
            "功能",
            "函数",
        ],
        ComplexityLevel.LOW: ["simple", "basic", "quick", "easy", "简单", "基础", "快速"],
    }

    # 紧急性关键词
    URGENCY_KEYWORDS: ClassVar[dict[UrgencyLevel, list[str]]] = {
        UrgencyLevel.CRITICAL: [
            "critical",
            "urgent",
            "security",
            "vulnerability",
            "关键",
            "紧急",
            "安全",
            "漏洞",
        ],
        UrgencyLevel.HIGH: ["important", "priority", "high", "重要", "优先"],
    }

    @classmethod
    def analyze(cls, text: str) -> SkillAnalysis:
        """分析文本,提取特征"""

        analysis = SkillAnalysis()
        text_lower = text.lower()

        # 1. 提取关键词
        analysis.keywords = cls._extract_keywords(text)

        # 2. 检测 LLM 需求
        analysis.requires_llm = any(kw in text_lower for kw in cls.LLM_KEYWORDS)

        # 3. 检测复杂度
        for complexity, keywords in cls.COMPLEXITY_KEYWORDS.items():
            if any(kw in text_lower for kw in keywords):
                analysis.complexity = complexity
                break

        # 4. 基于文件结构的启发式(phase/step 丰富的技能通常更复杂)
        if (
            "## phases" in text_lower
            or "## steps" in text_lower
            or "## workflow" in text_lower
            or "## process" in text_lower
        ):
            analysis.complexity = ComplexityLevel.HIGH

        # 5. 检测紧急性
        for urgency, keywords in cls.URGENCY_KEYWORDS.items():
            if any(kw in text_lower for kw in keywords):
                analysis.urgency = urgency
                break

        return analysis

    @classmethod
    def _extract_keywords(cls, text: str) -> list[str]:
        """提取关键词(3+ 字符,过滤停用词)"""

        # 提取单词
        words = re.findall(r"\b\w{3,}\b", text.lower())

        # 过滤停用词
        keywords = [w for w in words if w not in cls.STOP_WORDS]

        # 统计频率
        counter = Counter(keywords)

        # 返回最常见的 5 个
        return [word for word, _ in counter.most_common(5)]


class SkillAutoConfigurator:
    """技能自动配置生成器"""

    def __init__(self) -> None:
        self.logger = logger

    def understand_and_configure(
        self, metadata: SkillMetadata, skill_content: str, scope: str = "project"
    ) -> AutoGeneratedConfig:
        """理解技能并生成配置

        Args:
            metadata: 技能元数据
            skill_content: SKILL.md 的内容
            scope: 安装范围(project/global)

        Returns:
            自动生成的配置
        """

        self.logger.info(f"Understanding skill: {metadata.id}")

        # Step 1: 分析技能
        analysis = self._analyze_skill(metadata, skill_content)

        # Step 2: 应用规则生成配置
        config = self._generate_config(metadata, analysis, scope)

        # Step 3: 生成路由规则
        config.routing_patterns = self._generate_routing_patterns(metadata, analysis)

        # Step 4: 计算优先级
        config.priority = self._calculate_priority(metadata, analysis)

        # Step 5: 生成 LLM 配置
        if analysis.requires_llm:
            config.llm_config = self._generate_llm_config(analysis)
            config.requires_llm = True

        # Step 6: 设置置信度
        config.confidence = self._calculate_confidence(analysis)
        config.analysis = analysis

        self.logger.info(
            f"Config generated: category={config.category}, "
            f"priority={config.priority}, confidence={config.confidence:.2f}"
        )

        return config

    def _analyze_skill(self, metadata: SkillMetadata, content: str) -> SkillAnalysis:
        """分析技能特征"""

        analysis = SkillAnalysis()

        # 基本信息
        analysis.skill_type = metadata.skill_type
        analysis.tags = metadata.tags or []

        # 关键词分析
        text = f"{metadata.name} {metadata.description} {content}"
        keyword_analysis = KeywordAnalyzer.analyze(text)

        analysis.keywords = keyword_analysis.keywords
        analysis.requires_llm = keyword_analysis.requires_llm
        analysis.complexity = keyword_analysis.complexity
        analysis.urgency = keyword_analysis.urgency

        # 推断类别
        analysis.primary_category = CategoryRules.infer_category(metadata, content)
        analysis.categories.append(analysis.primary_category)

        return analysis

    def _generate_config(
        self, metadata: SkillMetadata, analysis: SkillAnalysis, scope: str
    ) -> AutoGeneratedConfig:
        """生成基础配置"""

        config = AutoGeneratedConfig(
            skill_id=metadata.id,
            scope=scope,
        )

        # 设置类别
        config.category = analysis.primary_category

        # 应用类别规则
        category_config = CategoryRules.get_config(analysis.primary_category)

        # 应用技能类型规则
        SkillTypeRules.get_config(metadata.skill_type)

        # 合并配置
        if "urgency" in category_config:
            urgency = category_config["urgency"]
            if urgency == "critical":
                config.config_source = "rule_engine:critical"
            elif urgency == "high":
                config.config_source = "rule_engine:high"

        return config

    def _generate_routing_patterns(
        self, metadata: SkillMetadata, analysis: SkillAnalysis
    ) -> list[str]:
        """生成路由规则"""

        patterns = []

        # 1. 从关键词生成
        if analysis.keywords:
            for keyword in analysis.keywords[:3]:
                patterns.append(f".*{keyword}.*")

        # 2. 从技能 ID 生成
        skill_id_pattern = metadata.id.replace("-", ".*")
        patterns.append(f".*{skill_id_pattern}.*")

        # 3. 从类别生成
        category = analysis.primary_category
        if category == "debugging":
            patterns.append(".*(debug|error|bug).*")
        elif category == "testing":
            patterns.append(".*(test|verify|check).*")
        elif category == "review":
            patterns.append(".*(review|audit|quality).*")

        return patterns

    def _calculate_priority(self, metadata: SkillMetadata, analysis: SkillAnalysis) -> int:
        """计算优先级"""

        priority = 50  # 基础优先级

        # 1. 类别优先级
        category = analysis.primary_category
        category_config = CategoryRules.get_config(category)

        if "priority_range" in category_config:
            min_p, max_p = category_config["priority_range"]
            priority = (min_p + max_p) // 2

        # 2. 复杂度调整
        if analysis.complexity == ComplexityLevel.HIGH:
            priority += 10
        elif analysis.complexity == ComplexityLevel.LOW:
            priority -= 5

        # 3. 紧急性调整
        if analysis.urgency == UrgencyLevel.CRITICAL:
            priority += 20
        elif analysis.urgency == UrgencyLevel.HIGH:
            priority += 10

        # 4. 技能类型调整
        if metadata.skill_type == SkillType.HYBRID:
            priority += 5

        # 确保在合理范围
        return max(0, min(100, priority))

    def _generate_llm_config(self, analysis: SkillAnalysis) -> dict[str, Any]:
        """生成 LLM 配置"""

        category = analysis.primary_category
        category_config = CategoryRules.get_config(category)

        llm_config = category_config.get("llm", {})

        # 如果类别没有 LLM 配置,使用默认
        if not llm_config:
            llm_config = {
                "provider": "anthropic",
                "models": ["claude-sonnet-4-6-20250514"],
                "temperature": 0.5,
            }

        return llm_config

    def _calculate_confidence(self, analysis: SkillAnalysis) -> float:
        """计算配置置信度"""

        confidence = 0.5  # 基础置信度

        # 1. 有关键词增加置信度
        if analysis.keywords:
            confidence += 0.1

        # 2. 明确的类别增加置信度
        if analysis.primary_category != "development":
            confidence += 0.15

        # 3. 明确的紧急性增加置信度
        if analysis.urgency != UrgencyLevel.NORMAL:
            confidence += 0.1

        # 4. 需要 LLM 且能判断提供商增加置信度
        if analysis.requires_llm:
            confidence += 0.1

        return min(1.0, confidence)

    def save_config(self, config: AutoGeneratedConfig, output_dir: Path) -> Path:
        """保存配置到文件

        Args:
            config: 生成的配置
            output_dir: 输出目录

        Returns:
            配置文件路径
        """

        import yaml

        # 确保输出目录存在
        output_dir.mkdir(parents=True, exist_ok=True)

        # 准备配置数据
        config_data = {
            "skills": {
                config.skill_id: {
                    "priority": config.priority,
                    "enabled": config.enabled,
                    "scope": config.scope,
                    "category": config.category,
                    "routing": {
                        "patterns": config.routing_patterns,
                        "priority": config.priority,
                    },
                }
            }
        }

        # 如果需要 LLM
        if config.requires_llm and config.llm_config:
            config_data["skills"][config.skill_id]["llm"] = config.llm_config

        # 添加元数据（包括项目 hash 用于 scope 隔离）
        metadata: dict[str, Any] = {
            "auto_configured": True,
            "config_source": config.config_source,
            "confidence": config.confidence,
        }

        if config.scope == "project":
            import hashlib

            metadata["project_hash"] = hashlib.md5(str(Path.cwd().resolve()).encode()).hexdigest()[
                :12
            ]

        config_data["skills"][config.skill_id]["metadata"] = metadata

        # 写入文件
        config_file = output_dir / "auto-config.yaml"
        with config_file.open("w") as f:
            yaml.dump(config_data, f, default_flow_style=False)

        self.logger.info(f"Config saved to: {config_file}")

        return config_file


def understand_skill_from_file(skill_path: Path, scope: str = "project") -> AutoGeneratedConfig:
    """从技能文件生成配置(便捷函数)

    Args:
        skill_path: 技能目录路径
        scope: 安装范围

    Returns:
        生成的配置
    """

    from vibesop.core.skills.parser import parse_skill_md

    # 读取 SKILL.md
    skill_md = skill_path / "SKILL.md"
    if not skill_md.exists():
        raise FileNotFoundError(f"SKILL.md not found in {skill_path}")

    content = skill_md.read_text()
    metadata = parse_skill_md(skill_md)

    if not metadata:
        raise ValueError(f"Failed to parse metadata from {skill_md}")

    # 生成配置
    configurator = SkillAutoConfigurator()
    config = configurator.understand_and_configure(metadata, content, scope)

    return config
