"""Tests for HookInstaller."""

import stat
import sys
from pathlib import Path

import pytest

from vibesop.core.skills import SkillStorage
from vibesop.hooks import HookInstaller, HookPoint
from vibesop.installer import VibeSOPInstaller


class TestHookInstaller:
    """Test HookInstaller functionality."""

    def test_create_installer(self) -> None:
        """Test creating HookInstaller."""
        installer = HookInstaller()
        assert installer is not None
        assert installer.template_env is not None

    def test_install_hooks_claude_code(self, tmp_path: Path) -> None:
        """Test installing hooks for Claude Code."""
        installer = HookInstaller()

        results = installer.install_hooks("claude-code", tmp_path)

        # Should install 4 hooks (including route-interceptor)
        assert len(results) == 4
        assert "pre-session-end" in results
        assert "pre-tool-use" in results
        assert "post-session-start" in results
        assert "route-interceptor" in results

        # All should succeed
        assert all(results.values())

        # Check files exist
        assert (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert (tmp_path / "hooks" / "pre-tool-use.sh").exists()
        assert (tmp_path / "hooks" / "post-session-start.sh").exists()

    def test_install_hooks_opencode(self, tmp_path: Path) -> None:
        """Test installing hooks for OpenCode."""
        installer = HookInstaller()

        results = installer.install_hooks("opencode", tmp_path)

        # OpenCode supports post-session-start + route-interceptor
        assert len(results) == 2
        assert results.get("post-session-start") is True
        assert results.get("route-interceptor") is True

    def test_install_hooks_specific(self, tmp_path: Path) -> None:
        """Test installing specific hooks."""
        installer = HookInstaller()

        # Only install pre-session-end hook
        results = installer.install_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        assert len(results) == 1
        assert "pre-session-end" in results
        assert results["pre-session-end"]

        # Only this hook should be installed
        assert (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert not (tmp_path / "hooks" / "pre-tool-use.sh").exists()

    def test_install_hooks_unknown_platform(self, tmp_path: Path) -> None:
        """Test installing hooks for unknown platform."""
        installer = HookInstaller()

        results = installer.install_hooks("unknown-platform", tmp_path)

        # Should return empty dict
        assert results == {}

    def test_hook_executable(self, tmp_path: Path) -> None:
        """Test that installed hooks are executable."""
        installer = HookInstaller()

        installer.install_hooks("claude-code", tmp_path)

        # Check executable bit
        hook_path = tmp_path / "hooks" / "pre-session-end.sh"
        assert hook_path.exists()

        st_mode = hook_path.stat().st_mode
        if sys.platform != "win32":
            # Windows chmod only toggles read-only; hooks run via `bash <script>`.
            assert st_mode & stat.S_IXUSR  # Owner execute permission

    def test_hook_content(self, tmp_path: Path) -> None:
        """Test that hooks have correct content."""
        installer = HookInstaller()

        installer.install_hooks("claude-code", tmp_path)

        # Check hook content
        hook_path = tmp_path / "hooks" / "pre-session-end.sh"
        content = hook_path.read_text(encoding="utf-8")

        assert "#!/bin/bash" in content
        assert "Pre-session-end hook for claude-code" in content
        assert "Generated by VibeSOP" in content

    def test_uninstall_hooks(self, tmp_path: Path) -> None:
        """Test uninstalling hooks."""
        installer = HookInstaller()

        # First install hooks
        installer.install_hooks("claude-code", tmp_path)
        assert (tmp_path / "hooks" / "pre-session-end.sh").exists()

        # Then uninstall
        results = installer.uninstall_hooks("claude-code", tmp_path)

        assert len(results) == 4
        assert all(results.values())

        # Files should be removed
        assert not (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert not (tmp_path / "hooks" / "pre-tool-use.sh").exists()
        assert not (tmp_path / "hooks" / "route-interceptor.sh").exists()

    def test_install_preserves_non_utf8_existing_hook(self, tmp_path: Path) -> None:
        """A pre-existing hook encoded in GBK (not UTF-8) must not crash
        install with UnicodeDecodeError — it is not installer-generated,
        so it is left untouched."""
        installer = HookInstaller()
        hook_path = tmp_path / "hooks" / "pre-session-end.sh"
        hook_path.parent.mkdir(parents=True)
        hook_path.write_bytes("#!/bin/bash\n# 用户自定义 hook\n".encode("gbk"))

        results = installer.install_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        assert results["pre-session-end"] is True
        assert hook_path.read_bytes() == "#!/bin/bash\n# 用户自定义 hook\n".encode("gbk")

    def test_uninstall_pi_keeps_adapter_ts_extensions(self, tmp_path: Path) -> None:
        """pi's hook points map to extensions/*.ts — non-.sh targets belong
        to the platform adapter, so uninstall must not unlink them."""
        installer = HookInstaller()
        installer.install_hooks("pi", tmp_path)
        for name in ("vibesop-route.ts", "vibesop-track.ts"):
            ts = tmp_path / "extensions" / name
            ts.parent.mkdir(parents=True, exist_ok=True)
            ts.write_text("// adapter-rendered extension\n", encoding="utf-8")

        results = installer.uninstall_hooks("pi", tmp_path)

        assert all(results.values())
        assert (tmp_path / "extensions" / "vibesop-route.ts").exists()
        assert (tmp_path / "extensions" / "vibesop-track.ts").exists()

    def test_uninstall_opencode_keeps_markerless_route_hook(self, tmp_path: Path) -> None:
        """opencode's hook points map to hooks/vibesop-route.sh, rendered by
        the adapter (no installer marker) — uninstall must preserve it."""
        installer = HookInstaller()
        route_hook = tmp_path / "hooks" / "vibesop-route.sh"
        route_hook.parent.mkdir(parents=True)
        route_hook.write_text(
            "#!/bin/bash\n# real adapter-rendered route hook\nexec vibe route --hook\n",
            encoding="utf-8",
        )

        results = installer.uninstall_hooks("opencode", tmp_path)

        assert all(results.values())
        assert "exec vibe route --hook" in route_hook.read_text(encoding="utf-8")

    def test_uninstall_hooks_specific(self, tmp_path: Path) -> None:
        """Test uninstalling specific hooks."""
        installer = HookInstaller()

        # Install all hooks
        installer.install_hooks("claude-code", tmp_path)

        # Uninstall only pre-session-end
        results = installer.uninstall_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        assert len(results) == 1
        assert "pre-session-end" in results

        # Only this hook should be removed
        assert not (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert (tmp_path / "hooks" / "pre-tool-use.sh").exists()

    def test_verify_hooks(self, tmp_path: Path) -> None:
        """Test verifying hooks."""
        installer = HookInstaller()

        # Before installation
        results = installer.verify_hooks("claude-code", tmp_path)
        assert len(results) == 4
        assert not any(results.values())  # All should be False

        # After installation
        installer.install_hooks("claude-code", tmp_path)
        results = installer.verify_hooks("claude-code", tmp_path)

        assert len(results) == 4
        assert all(results.values())  # All should be True

    def test_verify_hooks_partial(self, tmp_path: Path) -> None:
        """Test verifying hooks with partial installation."""
        installer = HookInstaller()

        # Install only one hook
        installer.install_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        # Verify all hooks
        results = installer.verify_hooks("claude-code", tmp_path)

        assert results["pre-session-end"]  # Installed
        assert not results["pre-tool-use"]  # Not installed
        assert not results["post-session-start"]  # Not installed

    def test_create_hook_from_template(self, tmp_path: Path) -> None:
        """Test creating hook from template."""
        installer = HookInstaller()

        # Create a custom template
        template_path = tmp_path / "custom_hook.sh.j2"
        template_path.write_text("#!/bin/bash\necho 'Custom: {{ name }}'", encoding="utf-8")

        hook = installer.create_hook_from_template(
            "custom-hook",
            HookPoint.PRE_SESSION_END,
            template_path,
            template_vars={"name": "TestValue"},
        )

        assert hook.hook_name == "custom-hook"
        assert hook.hook_point == HookPoint.PRE_SESSION_END
        rendered = hook.render()
        assert "Custom: TestValue" in rendered

    def test_get_hook_template_path(self) -> None:
        """Test getting hook template path."""
        installer = HookInstaller()

        path = installer.get_hook_template_path(HookPoint.PRE_SESSION_END)

        assert path.name == "pre-session-end.sh.j2"
        assert "templates" in str(path)


class TestHookInstallerIntegration:
    """Integration tests for HookInstaller."""

    def test_full_lifecycle(self, tmp_path: Path) -> None:
        """Test complete hook lifecycle."""
        installer = HookInstaller()

        # Install
        install_results = installer.install_hooks("claude-code", tmp_path)
        assert all(install_results.values())

        # Verify
        verify_results = installer.verify_hooks("claude-code", tmp_path)
        assert all(verify_results.values())

        # Uninstall
        uninstall_results = installer.uninstall_hooks("claude-code", tmp_path)
        assert all(uninstall_results.values())

        # Verify removal
        verify_results = installer.verify_hooks("claude-code", tmp_path)
        assert not any(verify_results.values())

    def test_reinstall_hooks(self, tmp_path: Path) -> None:
        """Test reinstalling hooks (idempotent)."""
        installer = HookInstaller()

        # First installation
        results1 = installer.install_hooks("claude-code", tmp_path)
        assert all(results1.values())

        # Second installation (should overwrite)
        results2 = installer.install_hooks("claude-code", tmp_path)
        assert all(results2.values())

        # Verify still valid
        verify_results = installer.verify_hooks("claude-code", tmp_path)
        assert all(verify_results.values())

    def test_fallback_stub_does_not_clobber_existing_script(self, tmp_path: Path) -> None:
        """No template exists for route-interceptor, so only the fallback
        stub is available — it must never overwrite the real script a
        higher-fidelity writer already put on disk. Production sequence
        (`vibe quickstart`): adapter render_config_only writes the real
        vibesop-route.sh first, HookInstaller runs second."""
        installer = HookInstaller()
        real = tmp_path / "hooks" / "vibesop-route.sh"
        real.parent.mkdir(parents=True)
        real.write_text(
            "#!/bin/bash\n# real adapter-rendered route hook\nexec vibe route --hook\n",
            encoding="utf-8",
        )

        results = installer.install_hooks("claude-code", tmp_path)

        assert results.get("route-interceptor") is True
        assert "exec vibe route --hook" in real.read_text(encoding="utf-8")

        # Templated hooks still install normally alongside the preserved file.
        assert (tmp_path / "hooks" / "pre-tool-use.sh").exists()

    def test_kept_hook_chmod_failure_still_reports_success(
        self, tmp_path: Path, monkeypatch
    ) -> None:
        """A kept (non-installer-generated) hook whose chmod fails — read-only
        file, foreign owner — is still a successful keep: the chmod is
        best-effort and must not surface as an install failure."""
        installer = HookInstaller()
        kept = tmp_path / "hooks" / "pre-session-end.sh"
        kept.parent.mkdir(parents=True)
        kept.write_text("#!/bin/bash\n# user-managed hook\n", encoding="utf-8")

        real_chmod = Path.chmod

        def failing_chmod(self: Path, mode: int, *args, **kwargs):
            if self == kept:
                raise PermissionError("read-only file")
            return real_chmod(self, mode, *args, **kwargs)

        monkeypatch.setattr(Path, "chmod", failing_chmod)

        results = installer.install_hooks("claude-code", tmp_path)

        assert results.get("pre-session-end") is True
        assert "user-managed hook" in kept.read_text(encoding="utf-8")

    def test_multiple_platforms(self, tmp_path: Path) -> None:
        """Test installing hooks for multiple platforms."""
        installer = HookInstaller()

        # Install for different platforms
        claude_dir = tmp_path / "claude-code"
        opencode_dir = tmp_path / "opencode"

        claude_results = installer.install_hooks("claude-code", claude_dir)
        opencode_results = installer.install_hooks("opencode", opencode_dir)

        # Claude Code should have 4 hooks (including route-interceptor)
        assert len(claude_results) == 4
        assert all(claude_results.values())

        # OpenCode should have 2 hooks (post-session-start + route-interceptor)
        assert len(opencode_results) == 2
        assert opencode_results.get("post-session-start") is True
        assert opencode_results.get("route-interceptor") is True


class TestHookInstallerClobberE2E:
    """P1: inside ``VibeSOPInstaller.install`` the adapter renders the real
    hooks first and HookInstaller runs second — its template stubs must never
    overwrite the adapter-rendered files (opencode's vibesop-route.sh, pi's
    extensions/*.ts)."""

    @pytest.fixture
    def home(self, monkeypatch, tmp_path):
        home = tmp_path / "fake_home"
        home.mkdir()
        monkeypatch.setenv("HOME", str(home))
        monkeypatch.setenv("USERPROFILE", str(home))
        # SkillStorage binds its dirs from Path.home() at import time; point
        # them at the fake home so the install's skill sync stays hermetic.
        monkeypatch.setattr(SkillStorage, "CENTRAL_SKILLS_DIR", home / ".config" / "skills")
        monkeypatch.setattr(
            SkillStorage,
            "PLATFORM_SKILLS_DIRS",
            {p: home / ".skills" / p for p in SkillStorage.PLATFORM_SKILLS_DIRS},
        )
        # The pi adapter resolves project_root="." at render time and writes
        # AGENTS.md there — without this chdir the install leaks a rewrite of
        # the vibesop repo's own AGENTS.md (found 2026-08-31: the nvm bullet
        # silently vanished from the working tree after every full-suite run).
        monkeypatch.chdir(tmp_path)
        return home

    def test_opencode_route_hook_survives_install(self, home, tmp_path: Path) -> None:
        """opencode post-session-start has a bash template mapped to
        hooks/vibesop-route.sh — it must not clobber the adapter render."""
        config_dir = tmp_path / "opencode"
        result = VibeSOPInstaller().install("opencode", config_dir)
        assert result["success"], result["errors"]

        content = (config_dir / "hooks" / "vibesop-route.sh").read_text(encoding="utf-8")
        # Still the adapter-rendered route hook, not the template stub.
        assert "handle_query_for_hook" in content
        assert "Post-session-start hook for" not in content

    def test_pi_extensions_survive_install(self, home, tmp_path: Path) -> None:
        """pi pre-session-end/post-session-start have bash templates mapped
        to extensions/*.ts — the .ts files must not be rewritten as bash."""
        config_dir = tmp_path / "pi"
        result = VibeSOPInstaller().install("pi", config_dir)
        assert result["success"], result["errors"]

        # The adapter's project-root AGENTS.md lands inside the fixture cwd
        # (tmp), never in the vibesop repo checkout.
        assert (Path.cwd() / "AGENTS.md").exists()
        assert (Path.cwd() / "AGENTS.md").resolve().is_relative_to(tmp_path)

        for name, ts_marker in (
            ("vibesop-route.ts", "runVibeRoute"),
            ("vibesop-track.ts", "isSessionEndSignal"),
        ):
            content = (config_dir / "extensions" / name).read_text(encoding="utf-8")
            assert not content.startswith("#!"), f"{name} overwritten with a bash stub"
            assert "Generated by VibeSOP v" in content
            # Positive discriminator: a function name only the adapter-rendered
            # .ts template carries — the bash stub can never contain it.
            assert ts_marker in content, f"{name} lost the adapter-rendered {ts_marker}"

    def test_reinstall_preserves_adapter_render(self, home, tmp_path: Path) -> None:
        """A forced reinstall must still not clobber the adapter-rendered hook."""
        installer = VibeSOPInstaller()
        config_dir = tmp_path / "opencode"
        assert installer.install("opencode", config_dir)["success"]
        assert installer.install("opencode", config_dir, force=True)["success"]

        content = (config_dir / "hooks" / "vibesop-route.sh").read_text(encoding="utf-8")
        assert "handle_query_for_hook" in content
