"""Tests for HookInstaller."""

import pytest
from pathlib import Path
import stat

from vibesop.hooks import HookInstaller, HookPoint


class TestHookInstaller:
    """Test HookInstaller functionality."""

    def test_create_installer(self) -> None:
        """Test creating HookInstaller."""
        installer = HookInstaller()
        assert installer is not None
        assert installer.template_env is not None

    def test_install_hooks_claude_code(self, tmp_path: Path) -> None:
        """Test installing hooks for Claude Code."""
        installer = HookInstaller()

        results = installer.install_hooks("claude-code", tmp_path)

        # Should install 3 hooks
        assert len(results) == 3
        assert "pre-session-end" in results
        assert "pre-tool-use" in results
        assert "post-session-start" in results

        # All should succeed
        assert all(results.values())

        # Check files exist
        assert (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert (tmp_path / "hooks" / "pre-tool-use.sh").exists()
        assert (tmp_path / "hooks" / "post-session-start.sh").exists()

    def test_install_hooks_opencode(self, tmp_path: Path) -> None:
        """Test installing hooks for OpenCode."""
        installer = HookInstaller()

        results = installer.install_hooks("opencode", tmp_path)

        # OpenCode doesn't support hooks
        assert len(results) == 0

    def test_install_hooks_specific(self, tmp_path: Path) -> None:
        """Test installing specific hooks."""
        installer = HookInstaller()

        # Only install pre-session-end hook
        results = installer.install_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        assert len(results) == 1
        assert "pre-session-end" in results
        assert results["pre-session-end"]

        # Only this hook should be installed
        assert (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert not (tmp_path / "hooks" / "pre-tool-use.sh").exists()

    def test_install_hooks_unknown_platform(self, tmp_path: Path) -> None:
        """Test installing hooks for unknown platform."""
        installer = HookInstaller()

        results = installer.install_hooks("unknown-platform", tmp_path)

        # Should return empty dict
        assert results == {}

    def test_hook_executable(self, tmp_path: Path) -> None:
        """Test that installed hooks are executable."""
        installer = HookInstaller()

        installer.install_hooks("claude-code", tmp_path)

        # Check executable bit
        hook_path = tmp_path / "hooks" / "pre-session-end.sh"
        assert hook_path.exists()

        st_mode = hook_path.stat().st_mode
        assert st_mode & stat.S_IXUSR  # Owner execute permission

    def test_hook_content(self, tmp_path: Path) -> None:
        """Test that hooks have correct content."""
        installer = HookInstaller()

        installer.install_hooks("claude-code", tmp_path)

        # Check hook content
        hook_path = tmp_path / "hooks" / "pre-session-end.sh"
        content = hook_path.read_text()

        assert "#!/bin/bash" in content
        assert "Pre-session-end hook for claude-code" in content
        assert "Generated by VibeSOP" in content

    def test_uninstall_hooks(self, tmp_path: Path) -> None:
        """Test uninstalling hooks."""
        installer = HookInstaller()

        # First install hooks
        installer.install_hooks("claude-code", tmp_path)
        assert (tmp_path / "hooks" / "pre-session-end.sh").exists()

        # Then uninstall
        results = installer.uninstall_hooks("claude-code", tmp_path)

        assert len(results) == 3
        assert all(results.values())

        # Files should be removed
        assert not (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert not (tmp_path / "hooks" / "pre-tool-use.sh").exists()

    def test_uninstall_hooks_specific(self, tmp_path: Path) -> None:
        """Test uninstalling specific hooks."""
        installer = HookInstaller()

        # Install all hooks
        installer.install_hooks("claude-code", tmp_path)

        # Uninstall only pre-session-end
        results = installer.uninstall_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        assert len(results) == 1
        assert "pre-session-end" in results

        # Only this hook should be removed
        assert not (tmp_path / "hooks" / "pre-session-end.sh").exists()
        assert (tmp_path / "hooks" / "pre-tool-use.sh").exists()

    def test_verify_hooks(self, tmp_path: Path) -> None:
        """Test verifying hooks."""
        installer = HookInstaller()

        # Before installation
        results = installer.verify_hooks("claude-code", tmp_path)
        assert len(results) == 3
        assert not any(results.values())  # All should be False

        # After installation
        installer.install_hooks("claude-code", tmp_path)
        results = installer.verify_hooks("claude-code", tmp_path)

        assert len(results) == 3
        assert all(results.values())  # All should be True

    def test_verify_hooks_partial(self, tmp_path: Path) -> None:
        """Test verifying hooks with partial installation."""
        installer = HookInstaller()

        # Install only one hook
        installer.install_hooks(
            "claude-code",
            tmp_path,
            hook_points=[HookPoint.PRE_SESSION_END],
        )

        # Verify all hooks
        results = installer.verify_hooks("claude-code", tmp_path)

        assert results["pre-session-end"]  # Installed
        assert not results["pre-tool-use"]  # Not installed
        assert not results["post-session-start"]  # Not installed

    def test_create_hook_from_template(self, tmp_path: Path) -> None:
        """Test creating hook from template."""
        installer = HookInstaller()

        # Create a custom template
        template_path = tmp_path / "custom_hook.sh.j2"
        template_path.write_text("#!/bin/bash\necho 'Custom: {{ name }}'")

        hook = installer.create_hook_from_template(
            "custom-hook",
            HookPoint.PRE_SESSION_END,
            template_path,
            template_vars={"name": "TestValue"},
        )

        assert hook.hook_name == "custom-hook"
        assert hook.hook_point == HookPoint.PRE_SESSION_END
        rendered = hook.render()
        assert "Custom: TestValue" in rendered

    def test_get_hook_template_path(self) -> None:
        """Test getting hook template path."""
        installer = HookInstaller()

        path = installer.get_hook_template_path(HookPoint.PRE_SESSION_END)

        assert path.name == "pre-session-end.sh.j2"
        assert "templates" in str(path)


class TestHookInstallerIntegration:
    """Integration tests for HookInstaller."""

    def test_full_lifecycle(self, tmp_path: Path) -> None:
        """Test complete hook lifecycle."""
        installer = HookInstaller()

        # Install
        install_results = installer.install_hooks("claude-code", tmp_path)
        assert all(install_results.values())

        # Verify
        verify_results = installer.verify_hooks("claude-code", tmp_path)
        assert all(verify_results.values())

        # Uninstall
        uninstall_results = installer.uninstall_hooks("claude-code", tmp_path)
        assert all(uninstall_results.values())

        # Verify removal
        verify_results = installer.verify_hooks("claude-code", tmp_path)
        assert not any(verify_results.values())

    def test_reinstall_hooks(self, tmp_path: Path) -> None:
        """Test reinstalling hooks (idempotent)."""
        installer = HookInstaller()

        # First installation
        results1 = installer.install_hooks("claude-code", tmp_path)
        assert all(results1.values())

        # Second installation (should overwrite)
        results2 = installer.install_hooks("claude-code", tmp_path)
        assert all(results2.values())

        # Verify still valid
        verify_results = installer.verify_hooks("claude-code", tmp_path)
        assert all(verify_results.values())

    def test_multiple_platforms(self, tmp_path: Path) -> None:
        """Test installing hooks for multiple platforms."""
        installer = HookInstaller()

        # Install for different platforms
        claude_dir = tmp_path / "claude-code"
        opencode_dir = tmp_path / "opencode"

        claude_results = installer.install_hooks("claude-code", claude_dir)
        opencode_results = installer.install_hooks("opencode", opencode_dir)

        # Claude Code should have hooks
        assert len(claude_results) == 3
        assert all(claude_results.values())

        # OpenCode should have no hooks
        assert len(opencode_results) == 0
