"""Cursor IDE platform adapter.

Refactored in v5.5.0 to inherit from FileBasedAdapter, sharing common logic
with OpenCode and Kimi CLI adapters.
"""

import json
import os
from pathlib import Path
from typing import Any

from vibesop.adapters.file_based import FileBasedAdapter
from vibesop.adapters.models import Manifest, RenderResult


class CursorAdapter(FileBasedAdapter):
    """Adapter for Cursor IDE platform."""

    def __init__(self, project_root: str | Path = ".") -> None:
        super().__init__()
        self._project_root = Path(project_root).resolve()

    @property
    def platform_name(self) -> str:
        return "cursor"

    @property
    def config_dir(self) -> Path:
        return Path("~/.config/cursor").expanduser()

    @property
    def platform_label(self) -> str:
        return "Cursor"

    @property
    def config_dir_label(self) -> str:
        return "~/.config/cursor"

    # ---- Provider detection ----
    def _detect_provider(self) -> str:
        explicit = os.getenv("VIBE_LLM_PROVIDER")
        if explicit and explicit in ("anthropic", "openai"):
            return explicit
        if os.getenv("ANTHROPIC_API_KEY"):
            return "anthropic"
        if os.getenv("OPENAI_API_KEY"):
            return "openai"
        return "anthropic"

    # ---- Config generation (Cursor-specific YAML format) ----
    def _generate_config(self, manifest: Manifest) -> str:
        from ruamel.yaml import YAML

        yaml = YAML()
        yaml.preserve_quotes = True
        yaml.default_flow_style = False

        config = {
            "version": manifest.metadata.version,
            "platform": manifest.metadata.platform,
            "generated": manifest.metadata.created_at.isoformat(),
            "security": {
                "scan_external_content": manifest.get_effective_security_policy().scan_external_content,
                "max_file_size_mb": manifest.get_effective_security_policy().max_file_size
                / (1024 * 1024),
            },
            "routing": {
                "enable_ai_routing": manifest.get_effective_routing_policy().enable_ai_routing,
                "confidence_threshold": manifest.get_effective_routing_policy().confidence_threshold,
            },
            "skills": [
                {
                    "id": skill.id,
                    "name": skill.name,
                    "description": skill.description,
                    "trigger": skill.trigger_when,
                }
                for skill in manifest.skills
            ],
        }
        if manifest.metadata.author:
            config["author"] = manifest.metadata.author
        if manifest.metadata.description:
            config["description"] = manifest.metadata.description

        from io import StringIO

        stream = StringIO()
        yaml.dump(config, stream)
        return stream.getvalue()

    def _generate_readme(self, manifest: Manifest) -> str:
        return (
            f"# Cursor Configuration\n\n"
            f"**Version**: {manifest.metadata.version}\n"
            f"**Generated**: {manifest.metadata.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n\n"
            "## Routing Protocol\n\n"
            "**MANDATORY: Call `vibe route` before any non-trivial task.**\n\n"
            "```bash\n"
            'vibe route "<user_request>"\n'
            "```\n\n"
            "Then read `skills/<matched-skill>/SKILL.md` and follow its steps.\n\n"
            "## Quick Commands\n\n"
            "```bash\n"
            'vibe route --slash "/vibe-help"\n'
            'vibe route --slash "/vibe-list"\n'
            'vibe route --slash "/vibe-install <pack>"\n'
            "```\n\n"
            "## Skills\n\n"
            "Run `vibe skills list` to see available skills.\n\n"
            "## IDE Integration\n\n"
            "Cursor IDE supports .cursorrules and AGENTS.md for AI instructions.\n"
            "VibeSOP skills are linked via symlinks to `~/.config/cursor/skills/`.\n\n"
            "```bash\n"
            "source ~/.config/cursor/vibesop-env.sh\n"
            "```\n\n"
            "---\n"
            "*Generated by VibeSOP*\n"
        )

    def _generate_llm_config(self) -> str:
        provider = self._detect_provider()
        config = {
            "version": "1.0.0",
            "default_provider": provider,
            "providers": {
                "anthropic": {
                    "api_key": os.getenv("ANTHROPIC_API_KEY", "YOUR_ANTHROPIC_API_KEY"),
                    "base_url": os.getenv("ANTHROPIC_BASE_URL", "https://api.anthropic.com"),
                    "models": {
                        "default": "claude-sonnet-4-20250514",
                        "fast": "claude-haiku-4-20250514",
                        "powerful": "claude-opus-4-20250514",
                    },
                    "timeout": 120,
                    "max_retries": 3,
                    "enabled": bool(os.getenv("ANTHROPIC_API_KEY")),
                },
                "openai": {
                    "api_key": os.getenv("OPENAI_API_KEY", "YOUR_OPENAI_API_KEY"),
                    "base_url": os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
                    "models": {
                        "default": "gpt-4o",
                        "fast": "gpt-4o-mini",
                        "powerful": "gpt-4o",
                    },
                    "timeout": 120,
                    "max_retries": 3,
                    "enabled": bool(os.getenv("OPENAI_API_KEY")),
                },
            },
            "routing": {
                "enable_ai_routing": True,
                "confidence_threshold": 0.75,
                "cache_enabled": True,
            },
            "preferences": {
                "preferred_model": "default",
                "stream_responses": True,
                "temperature": 0.7,
                "max_tokens": 4096,
            },
        }
        return json.dumps(config, indent=2)

    def _generate_env_script(self) -> str:
        from vibesop._version import __version__

        return (
            "#!/bin/bash\n"
            "# VibeSOP Environment Setup for Cursor IDE\n"
            f"# Generated by VibeSOP {__version__}\n"
            "#\n"
            "# Usage: source ~/.config/cursor/vibesop-env.sh\n"
            "# Cursor IDE will pick up AGENTS.md and .cursorrules automatically.\n\n"
            "# Generate a stable conversation ID for this project session\n"
            "if command -v python3 &> /dev/null; then\n"
            '    export CONVERSATION_ID="cursor-$(python3 -c '
            '"import os, hashlib; print(hashlib.sha256(os.getcwd().encode()).hexdigest()[:16])"'
            ')"\n'
            "fi\n\n"
            "# Wrap the vibe command to automatically pass --conversation\n"
            "vibe() {\n"
            '    if [ -n "$CONVERSATION_ID" ]; then\n'
            '        command vibe --conversation "$CONVERSATION_ID" "$@"\n'
            "    else\n"
            '        command vibe "$@"\n'
            "    fi\n"
            "}\n\n"
            "export -f vibe 2>/dev/null || true\n"
        )

    def _render_route_hook(self, output_dir: Path, result: RenderResult) -> None:
        """Render route hook with Cursor-specific parameters."""
        try:
            from vibesop.adapters._shared import render_route_hook as _shared_route_hook

            hook_content = _shared_route_hook(
                platform="cursor",
                platform_name="Cursor",
                purpose="Quick command handling and auto-routing for Cursor IDE",
                hook_event_name="",
                enable_explicit_overrides=True,
                enable_orchestration=True,
                include_additional_context=True,
                no_match_message=True,
            )
            hook_path = output_dir / "hooks" / "vibesop-route.sh"
            hook_path.parent.mkdir(parents=True, exist_ok=True)
            self.write_file_atomic(hook_path, hook_content, validate_security=False)
            hook_path.chmod(0o755)
            result.add_file(hook_path)
        except Exception as e:
            result.add_warning(f"Failed to write vibesop-route.sh for Cursor: {e}")

    def _render_env_script(self, output_dir: Path, result: RenderResult) -> None:
        """Render Cursor-specific env script."""
        try:
            script_path = output_dir / "vibesop-env.sh"
            self.write_file_atomic(
                script_path, self._generate_env_script(), validate_security=False
            )
            script_path.chmod(0o755)
            result.add_file(script_path)
        except Exception as e:
            result.add_warning(f"Failed to write vibesop-env.sh for Cursor: {e}")

    def get_settings_schema(self) -> dict[str, Any]:
        return {
            "$schema": "https://json.schemastore.org/claude-code-settings.json",
            "title": "Cursor Settings",
            "type": "object",
            "properties": {
                "editor": {
                    "type": "object",
                    "properties": {
                        "theme": {"type": "string"},
                        "fontSize": {"type": "integer"},
                    },
                },
                "security": {
                    "type": "object",
                    "properties": {
                        "scanContent": {"type": "boolean"},
                        "maxFileSize": {"type": "integer"},
                    },
                },
            },
        }
