"""Grok Build platform adapter.

Grok Build natively supports JSON hooks (``~/.grok/hooks/*.json``),
rules (``~/.grok/rules/*.md``), and skills (``~/.grok/skills/``).
This adapter deploys directly to ``~/.grok/`` without depending on
Claude Code compatibility shims.

Key differences from Claude Code adapter:
- JSON hook format (no shell script dependency; works on Windows native exe)
- ``~/.grok/rules/`` for always-loaded rules (Grok-native, not ``~/.claude/rules/``)
- ``~/.grok/skills/`` for skills (Grok-native)
- AGENTS.md is project-level, deployed separately by QuickBuilder
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from vibesop.adapters.base import PlatformAdapter
from vibesop.adapters.models import RenderResult

if TYPE_CHECKING:
    from vibesop.adapters.models import Manifest

logger = logging.getLogger(__name__)


class GrokBuildAdapter(PlatformAdapter):
    """Adapter for Grok Build platform.

    Deploys only routing rules and JSON hooks — does **not** manage
    ``~/.grok/skills/``, so orphan cleanup is disabled to avoid
    deleting Grok's own builtin skills.
    """

    def __init__(self, project_root: str | Path = ".") -> None:
        super().__init__()
        self._project_root = Path(project_root).resolve()

    cli_binary: str = "grok"

    # Grok Build adapter does NOT deploy skills (only rules + hooks).
    # The ``~/.grok/skills/`` directory may contain Grok's own builtin
    # skills — orphan cleanup must not touch them.
    manages_skills: bool = False

    @property
    def platform_name(self) -> str:
        return "grok-build"

    @property
    def config_dir(self) -> Path:
        return Path("~/.grok").expanduser()

    def render_config(self, manifest: Manifest, output_dir: Path) -> RenderResult:
        """Render Grok Build configuration.

        Generates:
          - ~/.grok/rules/routing.md (routing protocol, always loaded)
          - ~/.grok/hooks/vibesop-route.json (UserPromptSubmit hook)
        """
        result = self.create_render_result(success=True)

        try:
            errors = self.validate_manifest(manifest)
            if errors:
                for error in errors:
                    result.add_error(error)
                result.success = False
                return result

            output_dir.mkdir(parents=True, exist_ok=True)

            # --- rules/ ---
            rules_dir = output_dir / "rules"
            rules_dir.mkdir(exist_ok=True)

            routing_md = rules_dir / "routing.md"
            routing_md.write_text(self._render_routing_rule(), encoding="utf-8")
            result.add_file(routing_md)

            # --- hooks/ ---
            hooks_dir = output_dir / "hooks"
            hooks_dir.mkdir(exist_ok=True)

            hook_file = hooks_dir / "vibesop-route.json"
            hook_file.write_text(self._render_hook_json(), encoding="utf-8")
            result.add_file(hook_file)

            result.success = True

        except Exception as e:
            result.add_error(f"Render failed: {e}")
            result.success = False

        return result

    def validate_manifest(self, manifest: Manifest) -> list[str]:
        errors: list[str] = []
        meta = manifest.metadata
        if meta.platform != "grok-build":
            errors.append(
                f"Platform mismatch: expected 'grok-build', got '{meta.platform}'"
            )
        return errors

    def get_settings_schema(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "hooks": {
                    "type": "object",
                    "description": "UserPromptSubmit hook — calls vibe route",
                },
            },
        }

    # -- Private helpers ------------------------------------------------------

    @staticmethod
    def _render_routing_rule() -> str:
        return """# VibeSOP Routing Protocol

> **Generated by VibeSOP** — Grok Build native adapter

## Mandatory Routing

**Before every non-trivial task, call `vibe route` to find the best skill.**

```bash
vibe route "<user_request>"
```

Then read the matched skill's SKILL.md and follow its instructions.

## How It Works

1. You type a request in Grok Build.
2. The `vibesop-route` hook intercepts it via `UserPromptSubmit`.
3. `vibe route` matches the best skill from 50+ available.
4. The skill's instructions are injected into your context.

## Supported Commands

| Command | Purpose |
|---------|---------|
| `vibe route "<query>"` | Match best skill for a query |
| `vibe skills list` | List installed skills |
| `vibe doctor` | Check environment health |

## Session Lifecycle

When the user signals session end ("that's all", "收工", `/session-end`, etc.),
run `session-end` to flush session state.

For full documentation: read `docs/routing-protocol.md` in the VibeSOP project.
"""

    @staticmethod
    def _render_hook_json() -> str:
        hook_config = {
            "hooks": {
                "UserPromptSubmit": [
                    {
                        "matcher": "",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "vibe route --hook",
                                "timeout": 10,
                            }
                        ],
                    }
                ],
            },
        }
        return json.dumps(hook_config, indent=2) + "\n"
