"""Kimi Code CLI platform adapter.

Refactored in v5.5.0 to inherit from FileBasedAdapter, sharing common logic
with OpenCode and Cursor adapters.
"""

import logging
import re
from pathlib import Path
from typing import Any

from vibesop.adapters.file_based import FileBasedAdapter
from vibesop.adapters.models import Manifest, RenderResult

logger = logging.getLogger(__name__)


class KimiCliAdapter(FileBasedAdapter):
    """Adapter for Kimi Code CLI platform."""

    def __init__(self, project_root: str | Path = ".") -> None:
        super().__init__()
        self._project_root = Path(project_root).resolve()

    cli_binary = "kimi"

    @property
    def platform_name(self) -> str:
        return "kimi-cli"

    @property
    def config_dir(self) -> Path:
        return Path("~/.kimi-code").expanduser()

    @property
    def platform_label(self) -> str:
        return "Kimi Code CLI"

    @property
    def config_dir_label(self) -> str:
        return "~/.kimi-code"

    @property
    def config_format(self) -> str:
        return "toml"

    def build_prompt_chain(
        self,
        prompts: list[Any],
        output_dir: str | Path,
    ) -> str:
        """Write prompt chain files with Kimi CLI instructions."""
        from vibesop._version import __version__

        target = Path(output_dir)
        target.mkdir(parents=True, exist_ok=True)

        for pf in prompts:
            path = target / pf.filename
            self.write_file_atomic(path, pf.content, validate_security=False)

        readme = "# Prompt Chain — Kimi Code CLI\n\n"
        readme += "请按顺序读取每个阶段文件并执行其中的指令。\n\n"
        for pf in prompts:
            phase_label = "最终阶段" if pf.phase == -1 else f"Phase {pf.phase}"
            readme += f"- **{phase_label}**: `{pf.filename}`\n"
        readme += "\n```\n# 开始执行第一阶段\nread .vibe/prompts/phase-0-*.md\n```\n\n"
        readme += f"---\n*Generated by VibeSOP {__version__}*\n"

        readme_path = target / "README.md"
        self.write_file_atomic(readme_path, readme, validate_security=False)
        return str(readme_path)

    # ---- Hook configuration ----
    def _get_hook_event_name(self) -> str:
        return "UserPromptSubmit"

    def _get_include_additional_context(self) -> bool:
        return True

    def _get_no_match_message(self) -> bool:
        return True

    # ---- Config generation (TOML format) ----
    def _generate_config(self, manifest: Manifest) -> str:
        lines: list[str] = [
            "# VibeSOP Configuration for Kimi Code CLI",
            f"# Generated: {manifest.metadata.created_at.isoformat()}",
            f"# Version: {manifest.metadata.version}",
            f"# Platform: {manifest.metadata.platform}",
            "",
            "# ==============================================",
            "# IMPORTANT: Authentication Required",
            "# ==============================================",
            "#",
            "# This configuration requires API authentication.",
            "# Choose ONE of the following methods:",
            "#",
            "# Method 1: Use /login command (Recommended)",
            "#   1. Run: kimi",
            "#   2. Type: /login",
            "#   3. Follow browser authentication",
            "#",
            "# Method 2: Set environment variable",
            '#   export KIMI_API_KEY="sk-your-api-key"',
            "#",
            "# Method 3: Add api_key manually (Not recommended)",
            "#   [providers.kimi-for-coding]",
            '#   api_key = "sk-your-api-key"',
            "#",
            "# ==============================================",
            "",
            "",
        ]

        if manifest.metadata.author:
            lines.extend(
                [
                    f"# Author: {manifest.metadata.author}",
                    "",
                ]
            )
        if manifest.metadata.description:
            lines.extend(
                [
                    f"# Description: {manifest.metadata.description}",
                    "",
                ]
            )

        security = manifest.get_effective_security_policy()
        lines.extend(
            [
                "[vibesop.security]",
                f"scan_external_content = {str(security.scan_external_content).lower()}",
                f"max_file_size_mb = {security.max_file_size / (1024 * 1024):.1f}",
                "",
            ]
        )

        routing = manifest.get_effective_routing_policy()
        lines.extend(
            [
                "[vibesop.routing]",
                f"enable_ai_routing = {str(routing.enable_ai_routing).lower()}",
                f"confidence_threshold = {routing.confidence_threshold}",
                "",
            ]
        )

        if manifest.skills:
            lines.extend(
                [
                    "# VibeSOP Skills",
                    f"# {len(manifest.skills)} skills configured.",
                    "# Install them to ~/.kimi-code/skills/ (or .kimi-code/skills/ for project-level)",
                    "# and set merge_all_available_skills = true to load from multiple sources.",
                    "",
                ]
            )

        lines.extend(
            [
                "# ==============================================",
                "# VibeSOP Auto-Routing Hook",
                "# ==============================================",
                "#",
                "# This hook automatically calls 'vibe route' before each user prompt",
                "# to enable context-aware skill routing. Requires the hook script",
                "# to be installed at ~/.kimi-code/hooks/vibesop-route.sh",
                "#",
                "# NOTE: Kimi Code CLI event names vary by version. Valid values:",
                "#   - 'UserPromptSubmit' : before sending user message to AI",
                "#   - 'PreToolUse'       : before tool execution",
                "# Adjust the event below to match your Kimi Code CLI version.",
                "",
                "[[hooks]]",
                'name = "vibesop-route"',
                'event = "UserPromptSubmit"',
                'command = "bash ~/.kimi-code/hooks/vibesop-route.sh"',
                "",
            ]
        )

        return "\n".join(lines)

    def _merge_config_with_existing(self, config_path: Path, new_config: str) -> str:
        """Merge new VibeSOP config fragment into existing config.toml."""
        existing = config_path.read_text()
        lines = existing.split("\n")

        result_lines = []
        in_hooks_section = False
        for line in lines:
            if line.startswith("[[hooks]]"):
                in_hooks_section = True
                continue
            if in_hooks_section:
                if line.startswith("["):
                    in_hooks_section = False
                    result_lines.append(line)
                continue
            result_lines.append(line)

        while result_lines and result_lines[-1].strip() == "":
            result_lines.pop()

        hooks_match = re.search(r"(\[\[hooks\]\].*)", new_config, flags=re.DOTALL)
        if hooks_match:
            hooks_section = hooks_match.group(1).rstrip()
            result_lines.extend(["", "", hooks_section, ""])

        return "\n".join(result_lines)

    # ---- Custom config file rendering with merge support ----
    def _render_config_file(
        self, manifest: Manifest, output_dir: Path, result: RenderResult
    ) -> None:
        config_content = self._generate_config(manifest)
        config_path = output_dir / "config.toml"

        if config_path.exists():
            config_content = self._merge_config_with_existing(config_path, config_content)
        else:
            result.add_warning(
                "Kimi CLI first-time setup: "
                "1. Run 'kimi' to generate default config, "
                "2. Run '/login' to authenticate, "
                "3. Then run 'vibe switch kimi-cli -f' to add VibeSOP hooks"
            )

        self.write_file_atomic(config_path, config_content, validate_security=False)
        result.add_file(config_path)

    # ---- Override pipeline: Kimi has simpler render_config_only ----
    def render_config_only(
        self,
        manifest: Manifest,
        output_dir: Path,
    ) -> RenderResult:
        """Render configuration without skills.

        Kimi CLI has a simpler pipeline than other file-based adapters:
        no llm-config.json, no env script, no project-level AGENTS.md.
        AGENTS.md and docs/ are rendered in render_config() instead.
        """
        result = self.create_render_result(success=True)

        try:
            errors = self.validate_manifest(manifest)
            if errors:
                for error in errors:
                    result.add_error(error)
                result.success = False
                return result

            output_dir = self.ensure_output_dir(output_dir)

            # 1. Config file (TOML with merge support)
            self._render_config_file(manifest, output_dir, result)

            # 2. README if skills exist
            if manifest.skills:
                readme_content = self._generate_readme(manifest)
                readme_path = output_dir / "README.md"
                self.write_file_atomic(readme_path, readme_content, validate_security=False)
                result.add_file(readme_path)

            # 3. Route hook
            self._render_route_hook(output_dir, result)

        except Exception as e:
            result.add_error(str(e))
            result.success = False

        return result

    def render_config(self, manifest: Manifest, output_dir: Path) -> RenderResult:
        """Full render: config + skills + AGENTS.md + docs."""
        result = self.render_config_only(manifest, output_dir)
        if not result.success:
            return result

        try:
            # Render skill definitions
            skills_dir = output_dir / "skills"
            for skill in manifest.skills:
                dir_name = skill.id.replace("/", "-")
                skill_dir = skills_dir / dir_name
                skill_dir.mkdir(parents=True, exist_ok=True)
                self._render_skill_content(
                    skill,
                    skill_dir,
                    result,
                    dir_name=dir_name,
                    manifest=manifest,
                )

            # AGENTS.md context file
            agents_content = self._generate_agents_md(manifest)
            agents_path = output_dir / "AGENTS.md"
            self.write_file_atomic(agents_path, agents_content, validate_security=False)
            result.add_file(agents_path)

            # Docs files
            from vibesop.adapters._shared import render_docs_files

            docs_paths = render_docs_files(output_dir, manifest.skills)
            for doc_path in docs_paths:
                result.add_file(doc_path)

        except Exception as e:
            result.add_error(f"Failed to render skills: {e}")
            result.success = False

        return result

    # ---- Kimi-specific generators ----
    def _generate_readme(self, manifest: Manifest) -> str:
        lines = [
            "# Kimi Code CLI Configuration",
            "",
            f"**Version**: {manifest.metadata.version}",
            f"**Generated**: {manifest.metadata.created_at.strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## CRITICAL AGENT INSTRUCTION",
            "",
            "**Do NOT guess or hallucinate rules.** When you need information from any category below, you **MUST** use the appropriate tool to fetch the file contents before proceeding.",
            "",
            "## AI-Powered Skill Routing",
            "",
            "**⚠️ MANDATORY: ALWAYS call vibe route before starting ANY non-trivial task**",
            "This is NOT optional — routing ensures the correct skill is loaded for the task.",
            "",
            "### MANDATORY Workflow (必须遵循 - 无条件执行)",
            "",
            "**Step 1**: Call routing to get recommendations",
            '```bash\nvibe route "<user_request>"\n```',
            "",
            "**Step 2**: Read the recommended skill file ⚠️ CRITICAL STEP",
            "```markdown\nread skills/<matched-skill>/SKILL.md\n```",
            "",
            "**Step 3**: Execute according to the skill's steps",
            "- Do not skip skill definitions",
            "- Strictly follow the workflow described in the skill",
            "",
            "**Step 4**: Run verification after completion",
            "```bash\n# Run appropriate verification commands as required by the skill\n```",
            "",
            "### Multi-Intent Handling (多意图处理)",
            "",
            "If `vibe route` detects multiple intents, it will return an execution plan.",
            "You MUST:",
            "- Follow the plan steps in order",
            "- Read each step's SKILL.md before executing",
            "- Report completion after each step",
            "- Parallel steps can be executed simultaneously",
            "",
            "Example:",
            "```bash",
            '# User: "分析架构并优化性能"',
            "# vibe route returns execution plan:",
            "#   Step 1: superpowers-architect — Analyze architecture",
            "#   Step 2: superpowers-optimize — Optimize performance",
            "#",
            "# Execution:",
            "# 1. Read superpowers-architect/SKILL.md",
            "# 2. Follow architect workflow",
            '# 3. Report: "步骤 1 完成"',
            "# 4. Read superpowers-optimize/SKILL.md",
            "# 5. Follow optimize workflow",
            '# 6. Report: "步骤 2 完成"',
            "```",
            "",
            "### Workflow Patterns (v6.2.0)",
            "",
            "VibeSOP supports 6 workflow patterns for complex multi-step tasks:",
            "",
            "| Pattern | Behavior |",
            "|---------|----------|",
            "| `SEQUENTIAL` | Execute steps in dependency order |",
            "| `PARALLEL` | Steps are independent, executed sequentially on Kimi CLI |",
            "| `FAN_OUT` | Distribute one task across multiple perspectives |",
            "| `ADVERSARIAL` | Execute, then independently verify output |",
            "| `LOOP_UNTIL_DRY` | Iterate until no new findings emerge |",
            "| `TOURNAMENT` | Compare candidates pairwise, select best |",
            "",
            "```bash",
            "# Force a workflow pattern",
            'vibe route --pattern fan_out "分析架构并优化性能"',
            "# Enable adversarial verification",
            'vibe route --verify "重构认证模块"',
            "```",
            "",
            "### Fallback Mode (降级处理)",
            "",
            "If no skill matches your request:",
            "- The system will show the closest candidates",
            "- You may continue with raw LLM mode",
            "- NEVER guess skill rules — always read SKILL.md",
            "",
            "### Quick Commands (快捷命令)",
            "",
            "When a user types a `/vibe-*` command, execute it directly with `vibe route --slash`:",
            "```bash",
            'vibe route --slash "/vibe-help"',
            'vibe route --slash "/vibe-list"',
            'vibe route --slash "/vibe-analyze --deep"',
            'vibe route --slash "/vibe-install superpowers"',
            "```",
            "",
            "Available quick commands:",
            "- `/vibe-help` — Show all available commands",
            "- `/vibe-list` — List installed skills and available packs",
            "- `/vibe-route <query>` — Force trigger routing with transparency",
            "- `/vibe-install <pack>` — Install a skill pack",
            "- `/vibe-analyze [--deep]` — Analyze project architecture",
            "- `/vibe-evaluate [--skill <id>]` — Evaluate skill quality",
            "- `/vibe-orchestrate <query>` — Multi-skill orchestration",
            "",
            "### Example",
            "```bash",
            '# Step 1: Get recommendation\nvibe route "帮我调试这个 bug"\n# Output: Matched skill: systematic-debugging (95% confidence)',
            "",
            "# Step 2: Read skill definition (MANDATORY)",
            "read skills/systematic-debugging/SKILL.md",
            "",
            "# Step 3: Follow systematic debugging workflow",
            "# Gather info → Identify patterns → Form hypotheses → Test → Fix root cause",
            "",
            "# Step 4: Run verification",
            "```",
            "",
            "**Why use AI routing?**",
            "- ✅ **Multi-layer matching** - keyword, TF-IDF, embedding, fuzzy",
            "- ✅ **Semantic understanding** - understands intent, not just keywords",
            "- ✅ **Preference learning** - gets better the more you use it",
            "- ✅ **Context-aware** - considers conversation history and recent work",
            "",
            "**10-Layer Routing System:**",
            "- **Layer 0**: Explicit override (`/review`, `use tdd`)",
            "- **Layer 1**: Scenario patterns (debug, review, refactor, etc.)",
            "- **Layer 2**: AI Semantic Triage (Haiku/GPT, optional)",
            "- **Layer 3**: Keyword matching (exact token matching)",
            "- **Layer 4**: TF-IDF semantic matching (cosine similarity)",
            "- **Layer 5**: Embedding-based matching (vector similarity)",
            "- **Layer 6**: Fuzzy matching (Levenshtein distance for typos)",
            "",
            "## Configuration",
            "",
            "This configuration was generated by VibeSOP for Kimi Code CLI.",
            "",
            "Kimi Code CLI loads skills automatically from:",
            "- `~/.kimi-code/skills/` (brand directory, highest priority)",
            "- `~/.config/agents/skills/` (generic directory)",
            "- `.kimi-code/skills/` (project-level, when inside project)",
            "",
            "AGENTS.md (if present in project root) is loaded as project context.",
            "",
            "Skills are compatible with the Agent Skills open standard.",
            "",
            "## Session Lifecycle Events",
            "",
            "Routing applies to **user tasks**. But some events are **Agent lifecycle",
            "signals** and MUST be handled even when `vibe route` does not return a",
            "confident match.",
            "",
            "### Session End",
            "",
            "When the user signals the end of a session, you MUST run `session-end`:",
            "",
            '**English signals**: "that\'s all for now", "heading out", "I\'m leaving",',
            '"I\'m done", "gotta go", "wrap it up", "call it a day"',
            "",
            '**Chinese signals**: "我要离开了", "先走了", "拜拜", "再见",',
            '"今天就到这里", "就到这里吧", "收工"',
            "",
            "**Explicit command**: `/session-end`",
            "",
            "**If routing fails** (short-query bypass, no confident match):",
            "- Do NOT skip session-end because `vibe route` returned fallback-llm",
            "- Run the skill directly: `read skills/session-end/SKILL.md` and execute",
            "- This is a P0 mandatory skill — skipping it is a protocol violation",
            "",
            "## Skills",
            "",
            "Run `vibe skills list` to see available skills, or read `docs/skills-catalog.md`.",
            "",
            "## Security",
            "",
            f"- Scan External Content: {manifest.get_effective_security_policy().scan_external_content}",
            f"- Max File Size: {manifest.get_effective_security_policy().max_file_size / (1024 * 1024):.1f} MB",
            "",
            "## Routing",
            "",
            f"- AI Routing: {manifest.get_effective_routing_policy().enable_ai_routing}",
            f"- Confidence Threshold: {manifest.get_effective_routing_policy().confidence_threshold}",
            "",
            "---",
            "*Generated by VibeSOP*",
        ]

        return "\n".join(lines)

    def _generate_agents_md(self, manifest: Manifest) -> str:
        """Generate slim AGENTS.md index for Kimi Code CLI."""
        from vibesop.adapters._shared import generate_slim_agents_index

        return generate_slim_agents_index(
            version=manifest.metadata.version,
            platform_name="Kimi Code CLI",
            config_dir_label="~/.kimi-code",
            include_skills_reference=True,
        )

    # ---- No-op: Kimi CLI doesn't use env scripts ----
    def _render_env_script(self, output_dir: Path, result: RenderResult) -> None:
        """Kimi CLI does not use environment scripts."""

    def get_settings_schema(self) -> dict[str, Any]:
        return {
            "$schema": "https://json.schemastore.org/kimi-cli-settings.json",
            "title": "Kimi Code CLI Settings",
            "type": "object",
            "properties": {
                "default_model": {
                    "type": "string",
                    "description": "Default model name",
                },
                "default_thinking": {
                    "type": "boolean",
                    "description": "Enable thinking mode by default",
                },
                "default_yolo": {
                    "type": "boolean",
                    "description": "Enable YOLO (auto-approve) mode by default",
                },
                "theme": {
                    "type": "string",
                    "enum": ["dark", "light"],
                    "description": "Terminal color theme",
                },
                "merge_all_available_skills": {
                    "type": "boolean",
                    "description": "Merge skills from all brand directories",
                },
                "loop_control": {
                    "type": "object",
                    "properties": {
                        "max_steps_per_turn": {"type": "integer"},
                        "max_retries_per_step": {"type": "integer"},
                        "reserved_context_size": {"type": "integer"},
                        "compaction_trigger_ratio": {"type": "number"},
                    },
                },
            },
        }
