// VibeSOP Plugin for OpenCode
// Generated by VibeSOP — AI-powered skill routing
//
// This is a reference implementation. OpenCode plugin APIs are experimental
// and may change. When OpenCode stabilizes its plugin interface, this template
// will be auto-generated by `vibe build opencode`.
//
// Installation (when supported):
//   1. Copy this file to ~/.opencode/plugin/vibesop/index.ts
//   2. Install dependencies: npm install @opencode-ai/plugin
//   3. Enable in OpenCode settings

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import type { Plugin } from "@opencode-ai/plugin";

const OPCODE_DIR = path.join(require("os").homedir(), ".opencode");
const STATE_FILE = path.join(OPCODE_DIR, ".vibesop-state.json");

interface VibeSOPState {
  activeSkill: Record<string, string>;
  activePlan: Record<string, string>;
  toolHistory: Record<string, Array<{ tool: string; args: any; timestamp: number }>>;
}

function readState(): VibeSOPState {
  try {
    if (fs.existsSync(STATE_FILE)) {
      return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
    }
  } catch {}
  return { activeSkill: {}, activePlan: {}, toolHistory: {} };
}

function writeState(state: VibeSOPState): void {
  try {
    fs.mkdirSync(path.dirname(STATE_FILE), { recursive: true });
    fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), "utf-8");
  } catch {}
}

interface RouteResult {
  mode?: string;
  primary?: { skill_id?: string; confidence?: number };
  execution_plan?: { steps?: Array<{ step_number: number; intent: string; skill_id: string; input_query?: string; dependencies?: string[] }>; original_query?: string };
  message?: string;
}

/**
 * VibeSOP OpenCode Plugin
 *
 * Provides automatic skill routing and context injection for OpenCode.
 * Mirrors the behavior of Claude Code's UserPromptSubmit hook.
 */
export default {
  // ── System Prompt Transform ──────────────────────────────────────
  // Inject active skill content into the system prompt before each turn
  "experimental.chat.system.transform": async (input, output) => {
    const sessionId = input.sessionID;

    // Check if there's an active skill for this session
    const activeSkill = await getActiveSkill(sessionId);
    if (activeSkill) {
      const skillContent = await loadSkillContent(activeSkill);
      if (skillContent) {
        output.system.push(
          `<vibesop-skill id="${activeSkill}">\n${skillContent}\n</vibesop-skill>`
        );
      }
    }

    // Check if there's an active execution plan
    const activePlan = await getActivePlan(sessionId);
    if (activePlan) {
      output.system.push(
        `<vibesop-plan>\n${activePlan}\n</vibesop-plan>`
      );
    }
  },

  // ── Message Intercept ────────────────────────────────────────────
  // Trigger VibeSOP routing on each user message
  "chat.message": async (input, output) => {
    const query = input.message?.text || "";

    // Skip short or meta queries (conservative filtering)
    if (!query || query.length < 10) return;
    if (/vibe\s+(route|skill|config)|why.*routing|how.*skill/i.test(query)) {
      return;
    }

    // Call VibeSOP routing
    const result = await routeWithVibeSOP(query, input.sessionID);

    if (!result) return;

    if (result.mode === "orchestrated" || result.mode === "orchestrate") {
      // Multi-intent: inject execution plan
      const planPrompt = buildExecutionPlanPrompt(result.execution_plan);
      await setActivePlan(input.sessionID, planPrompt);

      // Notify user
      await output.client?.tui?.showToast?.({
        title: "VibeSOP",
        message: `Detected ${result.execution_plan?.steps?.length || 0} intents. Execution plan ready.`,
        variant: "info",
      });
    } else if (result.primary && result.primary.skill_id !== "fallback-llm") {
      // Single skill: mark as active for next system.transform
      await setActiveSkill(input.sessionID, result.primary.skill_id);

      await output.client?.tui?.showToast?.({
        title: "VibeSOP",
        message: `Matched: ${result.primary.skill_id} (${Math.round((result.primary.confidence || 0) * 100)}%)`,
        variant: "success",
      });
    }
  },

  // ── Tool Execute Before ──────────────────────────────────────────
  // Track tool usage for session context
  "tool.execute.before": async (input, output) => {
    await recordToolUse(input.sessionID, input.tool, input.args);
  },
} satisfies Plugin;

// ── Helper Functions ───────────────────────────────────────────────

async function getActiveSkill(sessionId: string): Promise<string | null> {
  const state = readState();
  return state.activeSkill[sessionId] || null;
}

async function setActiveSkill(sessionId: string, skillId: string): Promise<void> {
  const state = readState();
  state.activeSkill[sessionId] = skillId;
  writeState(state);
}

async function loadSkillContent(skillId: string): Promise<string | null> {
  const skillPaths = [
    path.join(OPCODE_DIR, "skills", skillId, "SKILL.md"),
    path.join(OPCODE_DIR, "skills", skillId.replace("/", "-"), "SKILL.md"),
  ];
  for (const p of skillPaths) {
    try {
      if (fs.existsSync(p)) {
        return fs.readFileSync(p, "utf-8").slice(0, 3000);
      }
    } catch {}
  }
  return null;
}

async function getActivePlan(sessionId: string): Promise<string | null> {
  const state = readState();
  return state.activePlan[sessionId] || null;
}

async function setActivePlan(sessionId: string, plan: string): Promise<void> {
  const state = readState();
  state.activePlan[sessionId] = plan;
  writeState(state);
}

async function routeWithVibeSOP(query: string, sessionId: string): Promise<RouteResult | null> {
  try {
    const convArg = sessionId ? `--conversation "${sessionId.slice(0, 16)}"` : "";
    const cmd = `vibe route ${convArg} --json "${query.replace(/"/g, '\\"')}" 2>/dev/null`;
    const output = execSync(cmd, { timeout: 5000, encoding: "utf-8" });
    return JSON.parse(output) as RouteResult;
  } catch {
    return null;
  }
}

async function recordToolUse(sessionId: string, tool: string, args: any): Promise<void> {
  const state = readState();
  if (!state.toolHistory[sessionId]) {
    state.toolHistory[sessionId] = [];
  }
  state.toolHistory[sessionId].push({ tool, args, timestamp: Date.now() });
  // Keep last 100 entries per session
  if (state.toolHistory[sessionId].length > 100) {
    state.toolHistory[sessionId] = state.toolHistory[sessionId].slice(-100);
  }
  writeState(state);
}

function buildExecutionPlanPrompt(plan: any): string {
  if (!plan || !plan.steps) return "";

  const lines = [
    `# Execution Plan: ${plan.original_query || "Multi-intent task"}`,
    "",
    "You MUST execute the following steps in order:",
    "",
  ];

  for (const step of plan.steps) {
    lines.push(`## Step ${step.step_number}: ${step.intent}`);
    lines.push(`- Skill: ${step.skill_id}`);
    lines.push(`- Task: ${step.input_query || step.intent}`);
    if (step.dependencies?.length) {
      lines.push(`- Depends on: ${step.dependencies.join(", ")}`);
    }
    lines.push(`- Report: "Step ${step.step_number} completed"`);
    lines.push("");
  }

  lines.push("---");
  lines.push("Rules:");
  lines.push("1. Read each step's SKILL.md before executing");
  lines.push("2. Follow the skill workflow strictly");
  lines.push("3. Report completion after each step");
  lines.push("4. Parallel steps may be executed simultaneously");

  return lines.join("\n");
}
