"""Execution summary generator for orchestration plans.

Converts ExecutionPlan into human-readable instructions for AI Agents.
"""

from __future__ import annotations

from vibesop.core.models import ExecutionMode, ExecutionPlan, ExecutionStep


def generate_execution_summary(plan: ExecutionPlan) -> str:
    """Generate a human-readable execution summary from a plan.

    Returns a markdown-formatted string with step-by-step instructions
    that an AI Agent (Claude Code, OpenCode, etc.) can follow.

    Example:
        >>> plan = router.orchestrate("分析并优化架构").execution_plan
        >>> print(generate_execution_summary(plan))
        # Step 1: architecture analysis
        # ...
    """
    lines: list[str] = []
    lines.append(f"# Execution Plan: {plan.original_query}")
    lines.append("")
    lines.append(f"**Strategy:** {plan.execution_mode.value.upper()}")
    lines.append(f"**Steps:** {len(plan.steps)}")
    lines.append("")

    if plan.reasoning:
        lines.append(f"> {plan.reasoning}")
        lines.append("")

    # Group steps by parallel batches if applicable
    if plan.execution_mode == ExecutionMode.PARALLEL:
        lines.append("## Parallel Execution")
        lines.append("")
        lines.append("The following steps can be executed simultaneously:")
        lines.append("")
        for step in plan.steps:
            lines.extend(_format_step(step))
    elif plan.execution_mode == ExecutionMode.SEQUENTIAL:
        lines.append("## Sequential Execution")
        lines.append("")
        lines.append("Execute the following steps in order:")
        lines.append("")
        for step in plan.steps:
            lines.extend(_format_step(step, show_dependencies=True))
    else:
        # MIXED mode
        groups = plan.get_parallel_groups()
        lines.append("## Mixed Execution")
        lines.append("")
        for batch_num, group in enumerate(groups, 1):
            if len(group) == 1:
                lines.append(f"### Batch {batch_num}: Sequential")
            else:
                lines.append(f"### Batch {batch_num}: Parallel ({len(group)} steps)")
            lines.append("")
            for step in group:
                lines.extend(_format_step(step, indent=2))
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by VibeSOP*")

    return "\n".join(lines)


def _format_step(
    step: ExecutionStep,
    show_dependencies: bool = False,
    indent: int = 0,
) -> list[str]:
    """Format a single step as markdown lines."""
    prefix = "  " * indent
    lines: list[str] = []

    lines.append(f"{prefix}### Step {step.step_number}: {step.intent}")
    lines.append(f"{prefix}- **Skill:** `{step.skill_id}`")
    lines.append(f"{prefix}- **Query:** {step.input_query}")

    if show_dependencies and step.dependencies:
        deps = ", ".join(step.dependencies)
        lines.append(f"{prefix}- **Depends on:** {deps}")

    if step.can_parallel:
        lines.append(f"{prefix}- **Can run in parallel:** Yes")

    lines.append("")
    return lines
