"""Tests for the shared hook template rendering.

Verifies that ``render_route_hook()`` in ``_shared.py`` produces valid
shell scripts that delegate to AgentRuntime.handle_query_for_hook().
"""

from pathlib import Path

import pytest

from vibesop.adapters._shared import render_route_hook


def _bash_path(path: Path) -> str:
    """Native path -> colon-safe Git Bash PATH entry.

    ``as_posix()`` alone is not enough on Windows: ``C:/x/y`` still contains
    the drive-letter colon, and bash splits PATH on ``:`` — the entry
    shatters into ``C`` and ``/x/y`` (which does not exist under the MSYS
    root). Git Bash resolves MSYS form ``/c/x/y``.
    """
    s = path.resolve().as_posix()
    if len(s) > 1 and s[1] == ":":
        s = "/" + s[0].lower() + s[2:]
    return s


class TestRenderRouteHook:
    """Tests for ``render_route_hook()``."""

    def test_default_params(self) -> None:
        """Default parameters produce a valid shell script."""
        result = render_route_hook()
        assert result.startswith("#!/bin/bash")
        assert "VibeSOP route hook for OpenCode" in result
        assert "AgentRuntime" in result
        assert "handle_query_for_hook" in result

    def test_claude_code_config(self) -> None:
        """Claude Code config passes hook params to AgentRuntime."""
        result = render_route_hook(
            platform="claude-code",
            platform_name="Claude Code",
            purpose="Trigger VibeSOP routing and inject skill context",
            hook_event_name="UserPromptSubmit",
            enable_explicit_overrides=True,
            enable_orchestration=True,
            include_additional_context=True,
            no_match_message=True,
        )
        assert result.startswith("#!/bin/bash")
        assert "VibeSOP route hook for Claude Code" in result
        assert "AgentRuntime" in result
        assert "handle_query_for_hook" in result
        assert "include_additional_context=True" in result
        assert "no_match_message=True" in result
        assert "UserPromptSubmit" in result

    def test_opencode_config(self) -> None:
        """OpenCode config passes hook params to AgentRuntime."""
        result = render_route_hook(
            platform="opencode",
            platform_name="OpenCode",
            purpose="Quick command handling and auto-routing for OpenCode",
            enable_explicit_overrides=False,
            enable_orchestration=False,
            include_additional_context=False,
            no_match_message=False,
        )
        assert result.startswith("#!/bin/bash")
        assert "VibeSOP route hook for OpenCode" in result
        assert "AgentRuntime" in result
        assert "include_additional_context=False" in result
        assert "no_match_message=False" in result

    def test_kimi_cli_config(self) -> None:
        """Kimi CLI config passes hook params to AgentRuntime."""
        result = render_route_hook(
            platform="kimi-cli",
            platform_name="Kimi CLI",
            purpose="Auto-routing via [[hooks]] in config.toml",
            hook_event_name="UserPromptSubmit",
            enable_explicit_overrides=False,
            enable_orchestration=False,
            include_additional_context=True,
            no_match_message=True,
        )
        assert result.startswith("#!/bin/bash")
        assert "VibeSOP route hook for Kimi CLI" in result
        assert "AgentRuntime" in result
        assert "include_additional_context=True" in result
        assert "no_match_message=True" in result

    def test_platforms_differ(self) -> None:
        """Each platform config produces distinct output."""
        claude = render_route_hook(platform="claude-code", platform_name="Claude Code")
        opencode = render_route_hook(platform="opencode", platform_name="OpenCode")
        kimi = render_route_hook(platform="kimi-cli", platform_name="Kimi CLI")
        assert "Claude Code" in claude
        assert "OpenCode" in opencode
        assert "Kimi CLI" in kimi
        assert claude != opencode
        assert claude != kimi

    def test_version_in_header(self) -> None:
        """Version string appears in the generated header."""
        result = render_route_hook(version="9.99.0")
        assert "Generated by VibeSOP v9.99.0" in result

    def test_custom_purpose(self) -> None:
        """Custom purpose appears in the header comment."""
        result = render_route_hook(purpose="my custom purpose")
        assert "my custom purpose" in result

    def test_invalid_platform(self) -> None:
        """Invalid platform still renders (template handles unknown gracefully)."""
        result = render_route_hook(platform="unknown-platform")
        assert result.startswith("#!/bin/bash")
        # Should not have any platform-specific usage block rendered
        assert "claude-code" not in result

    def test_no_bash_routing_logic(self) -> None:
        """Template must contain no routing logic — all in Python AgentRuntime."""
        result = render_route_hook(
            platform="claude-code",
            platform_name="Claude Code",
            enable_explicit_overrides=True,
            enable_orchestration=True,
            include_additional_context=True,
            no_match_message=True,
        )
        # These patterns were in the old 221-line bash hook
        assert "EXPLICIT SKILL" not in result
        assert "OVERRIDE" not in result
        assert "vibe route" not in result
        assert "CONVERSATION_ID" not in result
        assert "sha256sum" not in result
        assert "shasum" not in result
        assert "MODE=" not in result
        assert "PRIMARY=" not in result
        assert "SKILL_CONTENT=" not in result
        assert "ALTERNATIVES_JSON" not in result


class TestRouteHookSessionForwarding:
    """M12 M1: the route hook must forward the platform session_id so route
    spans join with tool-call telemetry captured under the same session."""

    def test_template_extracts_and_forwards_session_id(self) -> None:
        result = render_route_hook(
            platform="claude-code",
            platform_name="Claude Code",
            hook_event_name="UserPromptSubmit",
        )
        # jq extraction from the hook payload (both casings tolerated)
        assert ".session_id // .sessionId" in result
        assert "SESSION_ID=$(printf '%s' \"$INPUT\" | jq -r" in result
        # forwarded into handle_query_for_hook as the second positional arg
        assert "session_id=(sys.argv[2] if len(sys.argv) > 2 else '') or None" in result
        assert '"$QUERY" "$SESSION_ID"' in result

    def _run_rendered_script(self, tmp_path: Path, payload: str) -> str:
        """Execute the rendered route script hermetically and return stdout.

        The script prepends real system dirs (/opt/homebrew/bin, /usr/bin) to
        PATH, so ``python3``/``uv`` stubs on PATH never win. The uv-tool
        fallbacks (``bin/python`` or Windows ``Scripts/python.exe``) are
        the interpreters fully under our control — plant a stub there.
        From cwd=tmp_path the real ``uv run python -c "import vibesop"``
        probe fails (no project, no vibesop), so the stub is selected.
        """
        import shutil
        import subprocess

        jq = shutil.which("jq")
        bash = shutil.which("bash")
        if jq is None or bash is None:
            pytest.skip("bash/jq not available")

        home = tmp_path / "home"
        stub = home / ".local" / "share" / "uv" / "tools" / "vibesop" / "bin" / "python"
        stub.parent.mkdir(parents=True, exist_ok=True)
        stub.write_text(
            '#!/bin/sh\ncase "$*" in\n'
            "  *import\\ vibesop*) exit 0;;\n"
            "  *) printf 'STUBARGS:%s\\n' \"$*\";;\n"
            "esac\n",
            encoding="utf-8",
        )
        stub.chmod(0o755)

        script = tmp_path / "vibesop-route.sh"
        # newline="\n": vibe build writes LF; CRLF would smuggle \r into the
        # inline jq programs and the python -c code.
        script.write_text(
            render_route_hook(platform="claude-code", platform_name="Claude Code"),
            encoding="utf-8",
            newline="\n",
        )
        result = subprocess.run(
            [bash, str(script)],
            input=payload.encode(),
            capture_output=True,
            cwd=tmp_path,
            env={
                "HOME": str(home),
                # _bash_path(): Windows drive-letter colon would split the
                # bash PATH entry (C:/x -> "C" + "/x"); MSYS form /c/x
                # resolves. A broken entry silently skips jq extraction and
                # the tests then "pass" via the raw blob fallback.
                "PATH": f"/usr/bin:/bin:{_bash_path(Path(jq).parent)}",
            },
            timeout=60,
            check=False,
        )
        assert result.returncode == 0, result.stderr.decode()
        return result.stdout.decode()

    def test_rendered_script_passes_payload_session_id(self, tmp_path) -> None:
        """The payload's session_id reaches the Python invocation as argv[2]."""
        import json

        payload = json.dumps({"prompt": "hello stub test", "session_id": "abc-123-session"})
        out = self._run_rendered_script(tmp_path, payload)
        assert "STUBARGS:" in out
        assert "abc-123-session" in out
        assert "hello stub test" in out
        # Extraction really ran — the raw blob must not have fallen back
        # into QUERY (it would contain all substrings above).
        assert '"prompt"' not in out

    def test_rendered_script_without_session_id_passes_empty(self, tmp_path) -> None:
        """Payloads without session_id forward an empty string -> None."""
        import json

        out = self._run_rendered_script(tmp_path, json.dumps({"prompt": "hello no session"}))
        assert "STUBARGS:" in out
        assert "hello no session" in out
        assert '"prompt"' not in out

    def test_rendered_script_unpacks_content_block_array(self, tmp_path) -> None:
        """kimi -p sends the prompt as a content-block array; the extracted
        query must be the joined text, not the raw JSON blob (routing-
        precision audit 2026-08-29: the blob made the multi-intent detector
        fire on envelope noise like "type": "text")."""
        import json

        payload = json.dumps(
            {"prompt": [{"type": "text", "text": "评审这份设计文档"}], "session_id": "s-arr"}
        )
        out = self._run_rendered_script(tmp_path, payload)
        assert "评审这份设计文档" in out
        assert '"type"' not in out

    def test_rendered_script_joins_multiple_text_blocks(self, tmp_path) -> None:
        import json

        payload = json.dumps(
            {
                "prompt": [
                    {"type": "text", "text": "first block"},
                    {"type": "text", "text": "second block"},
                ]
            }
        )
        out = self._run_rendered_script(tmp_path, payload)
        assert "first block" in out
        assert "second block" in out
        assert '"type"' not in out

    def test_template_discovers_windows_uv_tool_python(self) -> None:
        result = render_route_hook(platform="claude-code", platform_name="Claude Code")
        assert "Scripts/python.exe" in result
        assert "WindowsApps" in result
        assert "uv tool dir" in result

    def test_rendered_script_uses_windows_scripts_python(self, tmp_path) -> None:
        """%APPDATA%/uv/tools/vibesop/Scripts/python.exe is a valid uv-tool layout."""
        import json
        import shutil
        import subprocess

        jq = shutil.which("jq")
        bash = shutil.which("bash")
        if jq is None or bash is None:
            pytest.skip("bash/jq not available")

        home = tmp_path / "home"
        appdata = home / "AppData" / "Roaming"
        # ``python.exe`` is also probed; a shebang stub must be named
        # ``python`` so Git Bash will exec it on Windows.
        stub = appdata / "uv" / "tools" / "vibesop" / "Scripts" / "python"
        stub.parent.mkdir(parents=True)
        stub.write_text(
            '#!/bin/sh\ncase "$*" in\n'
            "  *import\\ vibesop*) exit 0;;\n"
            "  *) printf 'STUBARGS:%s\\n' \"$*\";;\n"
            "esac\n",
            encoding="utf-8",
        )
        stub.chmod(0o755)

        script = tmp_path / "vibesop-route.sh"
        script.write_text(
            render_route_hook(platform="claude-code", platform_name="Claude Code"),
            encoding="utf-8",
            newline="\n",
        )
        result = subprocess.run(
            [bash, str(script)],
            input=json.dumps({"prompt": "windows uv tool", "session_id": "s-win"}).encode(),
            capture_output=True,
            cwd=tmp_path,
            env={
                "HOME": str(home),
                "APPDATA": str(appdata),
                "PATH": f"/usr/bin:/bin:{_bash_path(Path(jq).parent)}",
            },
            timeout=60,
            check=False,
        )
        assert result.returncode == 0, result.stderr.decode()
        out = result.stdout.decode()
        assert "STUBARGS:" in out
        assert "windows uv tool" in out
        assert "s-win" in out
        assert '"prompt"' not in out

    def test_rendered_script_empty_block_array_degrades_to_blank(self, tmp_path) -> None:
        import json

        """[] unpacks to blank (routed as a no-op), never back to the blob."""
        out = self._run_rendered_script(tmp_path, json.dumps({"prompt": []}))
        assert '"type"' not in out
        assert "STUBARGS:" in out

    def test_rendered_script_image_only_array_degrades_to_blank(self, tmp_path) -> None:
        import json

        """Non-text blocks unpack to blank; the blob must not leak back via
        the raw-stdin fallback (routing-precision audit round 2)."""
        out = self._run_rendered_script(
            tmp_path, json.dumps({"prompt": [{"type": "image", "source": {"id": "x"}}]})
        )
        assert '"type"' not in out
        assert "STUBARGS:" in out

    def test_rendered_script_object_prompt_unpacks_text(self, tmp_path) -> None:
        import json

        """A single content-block OBJECT envelope extracts .text too."""
        out = self._run_rendered_script(
            tmp_path, json.dumps({"prompt": {"type": "text", "text": "fix this bug"}})
        )
        assert "fix this bug" in out
        assert '"type"' not in out

    def test_rendered_script_object_prompt_without_text_degrades_to_blank(self, tmp_path) -> None:
        import json

        out = self._run_rendered_script(tmp_path, json.dumps({"prompt": {"type": "image"}}))
        assert '"type"' not in out
        assert "STUBARGS:" in out

    def test_rendered_script_preserves_leading_dash_payload(self, tmp_path) -> None:
        """Plain-text payloads starting with -n survive printf (echo would
        eat the flag and truncate the query)."""
        out = self._run_rendered_script(tmp_path, "-n hello plain text")
        assert "-n hello plain text" in out
